'use strict';
/* Level data. kind: 'snack' | 'veggie' | 'power'. content keys must exist in CONTENT (barrels.js).
   Levels 2-6 layouts drafted by qwen-fast sub-agent, validated headless (bounds, spacing, calorie budget). */

const LEVELS = [
  {
    name: 'First Breakfast',
    balls: 18,
    par: 13,
    goal: 93,
    barrels: [
      { x: 179, y: 228, kind: 'snack',   content: 'kibble' },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 228, kind: 'snack',   content: 'kibble' },
      { x: 140, y: 306, kind: 'veggie',  content: 'broccoli' },
      { x: 218, y: 306, kind: 'snack',   content: 'tuna', armor: true },
      { x: 374, y: 306, kind: 'snack',   content: 'salmon', armor: true },
      { x: 530, y: 306, kind: 'veggie',  content: 'celery' },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 462, kind: 'power',   content: 'wide' },
      { x: 530, y: 462, kind: 'power',   content: 'split' },
      { x: 296, y: 462, kind: 'snack',   content: 'kibble' },
      { x: 452, y: 462, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 335, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 540, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 540, kind: 'power',   content: 'multi' },
      { x: 491, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 384, kind: 'veggie',  content: 'broccoli' },
      { x: 62, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 384, kind: 'snack',   content: 'tuna', armor: true },
      { x: 374, y: 150, kind: 'snack',   content: 'kibble' },
      { x: 101, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 296, y: 306, kind: 'power',   content: 'multi' },
      { x: 218, y: 462, kind: 'snack',   content: 'kibble' },
      { x: 374, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 218, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 228, kind: 'power',   content: 'wide' },
    ],
  },
  {
    name: 'Pyramid Pounce',
    balls: 22,
    par: 14,
    goal: 94,
    barrels: [
      { x: 296, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 228, kind: 'veggie',  content: 'celery' },
      { x: 218, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 306, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 462, kind: 'power',   content: 'split' },
      { x: 413, y: 384, kind: 'power',   content: 'slow' },
      { x: 530, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 618, kind: 'power',   content: 'slow' },
      { x: 530, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 150, kind: 'snack',   content: 'tuna', armor: true },
      { x: 374, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 618, kind: 'power',   content: 'slow' },
      { x: 452, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 491, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 296, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 452, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 218, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 257, y: 228, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 228, kind: 'power',   content: 'split' },
      { x: 101, y: 540, kind: 'power',   content: 'split' },
    ],
  },
  {
    name: 'Diamond Darts',
    balls: 23,
    par: 16,
    goal: 166,
    barrels: [
      { x: 296, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 257, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon', armor: true },
      { x: 218, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 257, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 384, kind: 'power',   content: 'split' },
      { x: 530, y: 462, kind: 'power',   content: 'multi' },
      { x: 62, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 335, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 228, kind: 'snack',   content: 'salmon', armor: true },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 452, y: 462, kind: 'power',   content: 'multi' },
      { x: 413, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 374, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 218, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 374, y: 462, kind: 'power',   content: 'magnet' },
    ],
  },
  {
    name: 'Zigzag Zoom',
    balls: 25,
    par: 18,
    goal: 118,
    barrels: [
      { x: 62, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 452, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 150, kind: 'veggie',  content: 'celery' },
      { x: 140, y: 306, kind: 'snack',   content: 'salmon', armor: true },
      { x: 218, y: 306, kind: 'snack',   content: 'tuna', armor: true },
      { x: 374, y: 306, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 384, kind: 'power',   content: 'wide' },
      { x: 491, y: 384, kind: 'power',   content: 'slow' },
      { x: 140, y: 462, kind: 'power',   content: 'wide' },
      { x: 296, y: 462, kind: 'power',   content: 'wide' },
      { x: 374, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 618, kind: 'power',   content: 'split' },
      { x: 530, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 540, kind: 'power',   content: 'slow' },
      { x: 374, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 228, kind: 'snack',   content: 'tuna', armor: true },
      { x: 218, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 228, kind: 'power',   content: 'wide' },
      { x: 452, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 218, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 257, y: 384, kind: 'power',   content: 'wide' },
      { x: 452, y: 462, kind: 'power',   content: 'wide' },
      { x: 335, y: 540, kind: 'snack',   content: 'salmon' },
    ],
  },
  {
    name: 'Hexagon Hunt',
    balls: 27,
    par: 20,
    goal: 137,
    barrels: [
      { x: 257, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 218, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 257, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 374, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 335, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 62, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 335, y: 540, kind: 'power',   content: 'split' },
      { x: 413, y: 540, kind: 'power',   content: 'multi' },
      { x: 491, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 618, kind: 'snack',   content: 'salmon', armor: true },
      { x: 452, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 150, kind: 'power',   content: 'magnet' },
      { x: 101, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 374, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 618, kind: 'power',   content: 'multi' },
      { x: 491, y: 228, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 384, kind: 'veggie',  content: 'celery' },
    ],
  },
  {
    name: 'Diagonal Dash',
    balls: 29,
    par: 22,
    goal: 137,
    vacuum: true,
    barrels: [
      { x: 62, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 374, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 452, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 540, kind: 'power',   content: 'split' },
      { x: 296, y: 618, kind: 'power',   content: 'slow' },
      { x: 452, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 257, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 335, y: 540, kind: 'snack',   content: 'salmon', armor: true },
      { x: 413, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 413, y: 228, kind: 'power',   content: 'wide' },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 491, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 228, kind: 'snack',   content: 'tuna', armor: true },
      { x: 335, y: 384, kind: 'power',   content: 'wide' },
      { x: 491, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 218, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 306, kind: 'snack',   content: 'tuna' },
    ],
  },
  {
    name: 'Twin Peaks',
    balls: 29,
    par: 22,
    goal: 132,
    barrels: [
      { x: 179, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 452, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 306, kind: 'snack',   content: 'tuna', armor: true },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 306, kind: 'veggie',  content: 'broccoli' },
      { x: 530, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 413, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 384, kind: 'power',   content: 'split' },
      { x: 296, y: 462, kind: 'power',   content: 'multi' },
      { x: 62, y: 618, kind: 'power',   content: 'wide' },
      { x: 530, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 618, kind: 'power',   content: 'wide' },
      { x: 296, y: 150, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 540, kind: 'veggie',  content: 'broccoli' },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 462, kind: 'power',   content: 'wide' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 618, kind: 'snack',   content: 'tuna', armor: true },
    ],
  },
  {
    name: 'The Gauntlet',
    balls: 31,
    par: 23,
    goal: 72,
    barrels: [
      { x: 296, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 335, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 384, kind: 'veggie',  content: 'celery' },
      { x: 296, y: 618, kind: 'veggie',  content: 'celery' },
      { x: 257, y: 228, kind: 'veggie',  content: 'broccoli' },
      { x: 413, y: 228, kind: 'veggie',  content: 'celery' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 306, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 140, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'power',   content: 'slow' },
      { x: 140, y: 462, kind: 'power',   content: 'magnet' },
      { x: 452, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 530, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 384, kind: 'power',   content: 'split' },
      { x: 413, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 540, kind: 'snack',   content: 'salmon', armor: true },
      { x: 335, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 228, kind: 'veggie',  content: 'celery' },
      { x: 491, y: 540, kind: 'power',   content: 'slow' },
      { x: 530, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 530, y: 150, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 306, kind: 'power',   content: 'slow' },
    ],
  },
  {
    name: 'Honeycomb',
    balls: 32,
    par: 25,
    goal: 148,
    vacuum: true,
    barrels: [
      { x: 257, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 306, kind: 'snack',   content: 'salmon', armor: true },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 179, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 150, kind: 'veggie',  content: 'broccoli' },
      { x: 296, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 540, kind: 'power',   content: 'split' },
      { x: 62, y: 618, kind: 'power',   content: 'wide' },
      { x: 530, y: 618, kind: 'snack',   content: 'tuna', armor: true },
      { x: 140, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 540, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 462, kind: 'power',   content: 'wide' },
      { x: 101, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 618, kind: 'snack',   content: 'salmon', armor: true },
      { x: 140, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 462, kind: 'power',   content: 'wide' },
      { x: 179, y: 540, kind: 'snack',   content: 'salmon' },
    ],
  },
  {
    name: 'Veggie Minefield',
    balls: 32,
    par: 25,
    goal: 82,
    barrels: [
      { x: 101, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 228, kind: 'veggie',  content: 'broccoli' },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 228, kind: 'veggie',  content: 'broccoli' },
      { x: 140, y: 306, kind: 'snack',   content: 'tuna', armor: true },
      { x: 296, y: 306, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 384, kind: 'veggie',  content: 'broccoli' },
      { x: 257, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 384, kind: 'veggie',  content: 'broccoli' },
      { x: 491, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 462, kind: 'veggie',  content: 'celery' },
      { x: 452, y: 462, kind: 'power',   content: 'magnet' },
      { x: 218, y: 618, kind: 'power',   content: 'split' },
      { x: 374, y: 618, kind: 'snack',   content: 'tuna', armor: true },
      { x: 452, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 374, y: 462, kind: 'power',   content: 'magnet' },
      { x: 374, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 618, kind: 'power',   content: 'magnet' },
      { x: 530, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 150, kind: 'veggie',  content: 'broccoli' },
      { x: 218, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 413, y: 228, kind: 'veggie',  content: 'celery' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 530, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 491, y: 540, kind: 'veggie',  content: 'broccoli' },
      { x: 335, y: 540, kind: 'veggie',  content: 'celery' },
      { x: 101, y: 540, kind: 'veggie',  content: 'celery' },
    ],
  },
  {
    name: 'Power Tower',
    balls: 29,
    par: 22,
    goal: 121,
    barrels: [
      { x: 335, y: 228, kind: 'power',   content: 'multi' },
      { x: 296, y: 306, kind: 'snack',   content: 'tuna', armor: true },
      { x: 296, y: 462, kind: 'power',   content: 'wide' },
      { x: 335, y: 540, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 306, kind: 'snack',   content: 'salmon' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 491, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 306, kind: 'snack',   content: 'salmon', armor: true },
      { x: 452, y: 306, kind: 'power',   content: 'slow' },
      { x: 218, y: 618, kind: 'power',   content: 'magnet' },
      { x: 374, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 618, kind: 'power',   content: 'slow' },
      { x: 530, y: 618, kind: 'power',   content: 'split' },
      { x: 257, y: 384, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 618, kind: 'power',   content: 'slow' },
      { x: 179, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 374, y: 462, kind: 'snack',   content: 'salmon', armor: true },
      { x: 218, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 306, kind: 'power',   content: 'slow' },
      { x: 179, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 530, y: 462, kind: 'snack',   content: 'salmon' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 218, y: 306, kind: 'snack',   content: 'salmon', armor: true },
    ],
  },
  {
    name: 'The Grand Feast',
    balls: 40,
    par: 31,
    goal: 99,
    vacuum: true,
    barrels: [
      { x: 62, y: 150, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 228, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 150, kind: 'snack',   content: 'salmon', armor: true },
      { x: 452, y: 150, kind: 'snack',   content: 'tuna' },
      { x: 530, y: 150, kind: 'veggie',  content: 'broccoli' },
      { x: 140, y: 306, kind: 'veggie',  content: 'broccoli' },
      { x: 218, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 335, y: 228, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 101, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 384, kind: 'veggie',  content: 'broccoli' },
      { x: 335, y: 384, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 384, kind: 'snack',   content: 'salmon', armor: true },
      { x: 491, y: 384, kind: 'power',   content: 'multi' },
      { x: 179, y: 540, kind: 'power',   content: 'wide' },
      { x: 218, y: 462, kind: 'power',   content: 'split' },
      { x: 374, y: 462, kind: 'power',   content: 'magnet' },
      { x: 452, y: 462, kind: 'snack',   content: 'tuna' },
      { x: 218, y: 618, kind: 'snack',   content: 'tuna' },
      { x: 296, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 452, y: 618, kind: 'veggie',  content: 'broccoli' },
      { x: 62, y: 618, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 462, kind: 'power',   content: 'magnet' },
      { x: 140, y: 462, kind: 'power',   content: 'split' },
      { x: 491, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 257, y: 228, kind: 'snack',   content: 'tuna', armor: true },
      { x: 296, y: 462, kind: 'power',   content: 'split' },
      { x: 374, y: 306, kind: 'power',   content: 'magnet' },
      { x: 101, y: 540, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 540, kind: 'veggie',  content: 'broccoli' },
      { x: 491, y: 228, kind: 'power',   content: 'split' },
      { x: 296, y: 306, kind: 'snack',   content: 'salmon' },
    ],
  },
];
