'use strict';
/* Level data. kind: 'snack' | 'veggie' | 'power'. content keys must exist in CONTENT (barrels.js).
   Levels 2-6 layouts drafted by qwen-fast sub-agent, validated headless (bounds, spacing, calorie budget). */

const LEVELS = [
  {
    name: 'First Breakfast',
    balls: 18,
    par: 13,
    goal: 96,
    barrels: [
      { x: 150, y: 220, kind: 'snack',   content: 'kibble' },
      { x: 300, y: 200, kind: 'snack',   content: 'salmon' },
      { x: 450, y: 220, kind: 'snack',   content: 'kibble' },
      { x: 110, y: 330, kind: 'veggie',  content: 'broccoli' },
      { x: 235, y: 335, kind: 'snack',   content: 'tuna' },
      { x: 365, y: 335, kind: 'snack',   content: 'salmon' },
      { x: 495, y: 330, kind: 'veggie',  content: 'celery' },
      { x: 180, y: 445, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 445, kind: 'power',   content: 'wide' },
      { x: 538, y: 445, kind: 'power',   content: 'multi' },
      { x: 300, y: 460, kind: 'snack',   content: 'kibble' },
      { x: 420, y: 445, kind: 'veggie',  content: 'broccoli' },
      { x: 300, y: 550, kind: 'snack',   content: 'tuna' },
      { x: 353, y: 527, kind: 'snack',   content: 'tuna' },
      { x: 526, y: 532, kind: 'veggie',  content: 'broccoli' },
      { x: 234, y: 230, kind: 'snack',   content: 'tuna' },
      { x: 122, y: 468, kind: 'snack',   content: 'tuna' },
      { x: 172, y: 531, kind: 'power',   content: 'multi' },
      { x: 467, y: 406, kind: 'snack',   content: 'salmon' },
      { x: 121, y: 411, kind: 'snack',   content: 'tuna' },
      { x: 175, y: 344, kind: 'veggie',  content: 'broccoli' },
      { x: 66, y: 596, kind: 'veggie',  content: 'broccoli' },
      { x: 239, y: 404, kind: 'snack',   content: 'tuna' },
      { x: 359, y: 181, kind: 'snack',   content: 'kibble' },
      { x: 69, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 419, y: 524, kind: 'snack',   content: 'kibble' },
      { x: 284, y: 304, kind: 'veggie',  content: 'celery' },
      { x: 227, y: 480, kind: 'power',   content: 'multi' },
      { x: 361, y: 596, kind: 'snack',   content: 'kibble' },
      { x: 472, y: 588, kind: 'veggie',  content: 'celery' },
      { x: 186, y: 586, kind: 'veggie',  content: 'broccoli' },
      { x: 524, y: 238, kind: 'snack',   content: 'salmon' },
      { x: 356, y: 409, kind: 'power',   content: 'wide' },
    ],
  },
  {
    name: 'Pyramid Pounce',
    balls: 22,
    par: 14,
    goal: 145,
    barrels: [
      { x: 300, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 240, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 240, kind: 'snack',   content: 'salmon' },
      { x: 180, y: 300, kind: 'veggie',  content: 'celery' },
      { x: 300, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 300, kind: 'veggie',  content: 'celery' },
      { x: 120, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 240, y: 360, kind: 'snack',   content: 'tuna' },
      { x: 360, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 360, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 620, kind: 'power',   content: 'wide' },
      { x: 538, y: 620, kind: 'power',   content: 'slow' },
      { x: 459, y: 181, kind: 'veggie',  content: 'celery' },
      { x: 348, y: 584, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 296, kind: 'power',   content: 'slow' },
      { x: 113, y: 180, kind: 'veggie',  content: 'celery' },
      { x: 525, y: 297, kind: 'snack',   content: 'tuna' },
      { x: 226, y: 577, kind: 'snack',   content: 'salmon' },
      { x: 404, y: 589, kind: 'snack',   content: 'salmon' },
      { x: 517, y: 532, kind: 'snack',   content: 'tuna' },
      { x: 292, y: 580, kind: 'snack',   content: 'salmon' },
      { x: 474, y: 478, kind: 'snack',   content: 'salmon' },
      { x: 413, y: 518, kind: 'power',   content: 'slow' },
      { x: 244, y: 477, kind: 'veggie',  content: 'celery' },
      { x: 296, y: 240, kind: 'veggie',  content: 'celery' },
      { x: 130, y: 241, kind: 'snack',   content: 'tuna' },
      { x: 117, y: 527, kind: 'snack',   content: 'tuna' },
      { x: 121, y: 584, kind: 'veggie',  content: 'celery' },
      { x: 463, y: 242, kind: 'snack',   content: 'salmon' },
      { x: 464, y: 580, kind: 'veggie',  content: 'celery' },
      { x: 345, y: 521, kind: 'snack',   content: 'tuna' },
      { x: 526, y: 233, kind: 'power',   content: 'slow' },
      { x: 182, y: 533, kind: 'power',   content: 'wide' },
    ],
  },
  {
    name: 'Diamond Darts',
    balls: 23,
    par: 16,
    goal: 195,
    barrels: [
      { x: 300, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 240, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 240, kind: 'snack',   content: 'salmon' },
      { x: 180, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 120, y: 360, kind: 'veggie',  content: 'celery' },
      { x: 240, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 360, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 620, kind: 'power',   content: 'magnet' },
      { x: 538, y: 620, kind: 'power',   content: 'multi' },
      { x: 64, y: 518, kind: 'snack',   content: 'tuna' },
      { x: 126, y: 233, kind: 'snack',   content: 'tuna' },
      { x: 353, y: 520, kind: 'snack',   content: 'salmon' },
      { x: 465, y: 529, kind: 'snack',   content: 'tuna' },
      { x: 227, y: 534, kind: 'snack',   content: 'tuna' },
      { x: 521, y: 186, kind: 'snack',   content: 'salmon' },
      { x: 478, y: 241, kind: 'snack',   content: 'tuna' },
      { x: 178, y: 478, kind: 'snack',   content: 'tuna' },
      { x: 520, y: 518, kind: 'snack',   content: 'salmon' },
      { x: 476, y: 461, kind: 'snack',   content: 'salmon' },
      { x: 116, y: 584, kind: 'power',   content: 'multi' },
      { x: 357, y: 578, kind: 'snack',   content: 'salmon' },
      { x: 239, y: 472, kind: 'snack',   content: 'tuna' },
      { x: 123, y: 526, kind: 'snack',   content: 'tuna' },
      { x: 301, y: 479, kind: 'veggie',  content: 'celery' },
      { x: 238, y: 594, kind: 'snack',   content: 'tuna' },
      { x: 115, y: 299, kind: 'snack',   content: 'salmon' },
      { x: 402, y: 479, kind: 'snack',   content: 'tuna' },
      { x: 534, y: 289, kind: 'power',   content: 'magnet' },
    ],
  },
  {
    name: 'Zigzag Zoom',
    balls: 25,
    par: 18,
    goal: 208,
    barrels: [
      { x: 62, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 120, y: 280, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 280, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 280, kind: 'snack',   content: 'tuna' },
      { x: 480, y: 280, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 380, kind: 'veggie',  content: 'celery' },
      { x: 180, y: 380, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 380, kind: 'snack',   content: 'tuna' },
      { x: 538, y: 380, kind: 'veggie',  content: 'celery' },
      { x: 120, y: 480, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 480, kind: 'snack',   content: 'tuna' },
      { x: 480, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 620, kind: 'power',   content: 'wide' },
      { x: 538, y: 620, kind: 'power',   content: 'slow' },
      { x: 71, y: 527, kind: 'power',   content: 'wide' },
      { x: 406, y: 590, kind: 'power',   content: 'wide' },
      { x: 524, y: 239, kind: 'snack',   content: 'salmon' },
      { x: 229, y: 583, kind: 'snack',   content: 'tuna' },
      { x: 66, y: 299, kind: 'veggie',  content: 'celery' },
      { x: 464, y: 579, kind: 'power',   content: 'wide' },
      { x: 232, y: 416, kind: 'veggie',  content: 'celery' },
      { x: 534, y: 306, kind: 'snack',   content: 'tuna' },
      { x: 174, y: 462, kind: 'power',   content: 'slow' },
      { x: 244, y: 351, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 465, kind: 'snack',   content: 'tuna' },
      { x: 304, y: 461, kind: 'snack',   content: 'tuna' },
      { x: 356, y: 402, kind: 'power',   content: 'wide' },
      { x: 116, y: 416, kind: 'snack',   content: 'tuna' },
      { x: 528, y: 528, kind: 'snack',   content: 'salmon' },
      { x: 179, y: 236, kind: 'snack',   content: 'tuna' },
      { x: 465, y: 344, kind: 'snack',   content: 'tuna' },
      { x: 128, y: 589, kind: 'snack',   content: 'salmon' },
      { x: 296, y: 576, kind: 'snack',   content: 'tuna' },
      { x: 183, y: 538, kind: 'power',   content: 'wide' },
      { x: 114, y: 350, kind: 'power',   content: 'wide' },
      { x: 291, y: 236, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 421, kind: 'snack',   content: 'tuna' },
    ],
  },
  {
    name: 'Hexagon Hunt',
    balls: 27,
    par: 20,
    goal: 177,
    barrels: [
      { x: 300, y: 240, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 210, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 210, kind: 'snack',   content: 'salmon' },
      { x: 180, y: 240, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 240, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 240, y: 330, kind: 'snack',   content: 'tuna' },
      { x: 360, y: 330, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 120, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 480, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 520, kind: 'veggie',  content: 'celery' },
      { x: 180, y: 520, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 520, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 520, kind: 'snack',   content: 'tuna' },
      { x: 538, y: 520, kind: 'veggie',  content: 'celery' },
      { x: 62, y: 620, kind: 'power',   content: 'magnet' },
      { x: 538, y: 620, kind: 'power',   content: 'multi' },
      { x: 114, y: 479, kind: 'veggie',  content: 'celery' },
      { x: 293, y: 580, kind: 'snack',   content: 'tuna' },
      { x: 478, y: 523, kind: 'snack',   content: 'salmon' },
      { x: 112, y: 581, kind: 'snack',   content: 'salmon' },
      { x: 126, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 114, y: 236, kind: 'veggie',  content: 'celery' },
      { x: 236, y: 581, kind: 'snack',   content: 'salmon' },
      { x: 357, y: 577, kind: 'snack',   content: 'salmon' },
      { x: 478, y: 591, kind: 'power',   content: 'magnet' },
      { x: 531, y: 231, kind: 'snack',   content: 'salmon' },
      { x: 534, y: 361, kind: 'snack',   content: 'tuna' },
      { x: 462, y: 349, kind: 'snack',   content: 'tuna' },
      { x: 412, y: 591, kind: 'snack',   content: 'salmon' },
      { x: 230, y: 478, kind: 'snack',   content: 'salmon' },
      { x: 118, y: 301, kind: 'power',   content: 'multi' },
      { x: 518, y: 291, kind: 'snack',   content: 'salmon' },
      { x: 417, y: 405, kind: 'veggie',  content: 'celery' },
    ],
  },
  {
    name: 'Diagonal Dash',
    balls: 29,
    par: 22,
    goal: 217,
    vacuum: true,
    barrels: [
      { x: 62, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 220, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 260, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 340, kind: 'snack',   content: 'tuna' },
      { x: 120, y: 360, kind: 'snack',   content: 'tuna' },
      { x: 240, y: 400, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 440, kind: 'snack',   content: 'tuna' },
      { x: 480, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 520, kind: 'veggie',  content: 'celery' },
      { x: 180, y: 560, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 600, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 620, kind: 'snack',   content: 'tuna' },
      { x: 538, y: 620, kind: 'power',   content: 'wide' },
      { x: 62, y: 620, kind: 'power',   content: 'slow' },
      { x: 240, y: 520, kind: 'snack',   content: 'tuna' },
      { x: 360, y: 560, kind: 'snack',   content: 'salmon' },
      { x: 410, y: 529, kind: 'snack',   content: 'salmon' },
      { x: 474, y: 238, kind: 'veggie',  content: 'celery' },
      { x: 127, y: 468, kind: 'veggie',  content: 'celery' },
      { x: 71, y: 410, kind: 'snack',   content: 'tuna' },
      { x: 523, y: 286, kind: 'snack',   content: 'salmon' },
      { x: 170, y: 412, kind: 'veggie',  content: 'celery' },
      { x: 473, y: 410, kind: 'power',   content: 'wide' },
      { x: 352, y: 189, kind: 'snack',   content: 'salmon' },
      { x: 297, y: 404, kind: 'snack',   content: 'salmon' },
      { x: 536, y: 523, kind: 'snack',   content: 'tuna' },
      { x: 239, y: 583, kind: 'snack',   content: 'tuna' },
      { x: 243, y: 302, kind: 'veggie',  content: 'celery' },
      { x: 536, y: 417, kind: 'snack',   content: 'salmon' },
      { x: 182, y: 293, kind: 'snack',   content: 'tuna' },
      { x: 121, y: 295, kind: 'power',   content: 'wide' },
      { x: 187, y: 479, kind: 'snack',   content: 'tuna' },
      { x: 473, y: 577, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 293, kind: 'snack',   content: 'salmon' },
      { x: 348, y: 302, kind: 'snack',   content: 'salmon' },
      { x: 295, y: 466, kind: 'snack',   content: 'salmon' },
      { x: 127, y: 184, kind: 'snack',   content: 'tuna' },
      { x: 410, y: 236, kind: 'snack',   content: 'salmon' },
      { x: 411, y: 472, kind: 'snack',   content: 'salmon' },
      { x: 228, y: 184, kind: 'snack',   content: 'tuna' },
      { x: 119, y: 534, kind: 'snack',   content: 'tuna' },
    ],
  },
  {
    name: 'Twin Peaks',
    balls: 29,
    par: 22,
    goal: 154,
    barrels: [
      { x: 180, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 250, kind: 'snack',   content: 'salmon' },
      { x: 220, y: 250, kind: 'snack',   content: 'salmon' },
      { x: 380, y: 250, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 250, kind: 'snack',   content: 'salmon' },
      { x: 100, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 180, y: 320, kind: 'snack',   content: 'tuna' },
      { x: 260, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 340, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 320, kind: 'snack',   content: 'tuna' },
      { x: 500, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 390, kind: 'veggie',  content: 'broccoli' },
      { x: 220, y: 390, kind: 'snack',   content: 'salmon' },
      { x: 380, y: 390, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 390, kind: 'veggie',  content: 'celery' },
      { x: 300, y: 470, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 620, kind: 'power',   content: 'wide' },
      { x: 538, y: 620, kind: 'power',   content: 'multi' },
      { x: 300, y: 577, kind: 'power',   content: 'wide' },
      { x: 463, y: 460, kind: 'snack',   content: 'salmon' },
      { x: 362, y: 591, kind: 'snack',   content: 'salmon' },
      { x: 295, y: 186, kind: 'snack',   content: 'salmon' },
      { x: 523, y: 531, kind: 'snack',   content: 'salmon' },
      { x: 234, y: 537, kind: 'snack',   content: 'salmon' },
      { x: 349, y: 521, kind: 'power',   content: 'wide' },
      { x: 114, y: 471, kind: 'snack',   content: 'salmon' },
      { x: 536, y: 242, kind: 'snack',   content: 'salmon' },
      { x: 407, y: 530, kind: 'snack',   content: 'salmon' },
      { x: 533, y: 414, kind: 'veggie',  content: 'broccoli' },
      { x: 304, y: 406, kind: 'snack',   content: 'salmon' },
      { x: 119, y: 596, kind: 'snack',   content: 'salmon' },
      { x: 466, y: 581, kind: 'snack',   content: 'tuna' },
      { x: 242, y: 476, kind: 'power',   content: 'wide' },
      { x: 181, y: 596, kind: 'snack',   content: 'salmon' },
      { x: 64, y: 420, kind: 'snack',   content: 'tuna' },
    ],
  },
  {
    name: 'The Gauntlet',
    balls: 31,
    par: 23,
    goal: 101,
    barrels: [
      { x: 300, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 260, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 340, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 500, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 580, kind: 'snack',   content: 'salmon' },
      { x: 220, y: 220, kind: 'veggie',  content: 'celery' },
      { x: 380, y: 220, kind: 'veggie',  content: 'celery' },
      { x: 220, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 380, y: 300, kind: 'veggie',  content: 'broccoli' },
      { x: 220, y: 380, kind: 'veggie',  content: 'celery' },
      { x: 380, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 220, y: 460, kind: 'veggie',  content: 'broccoli' },
      { x: 380, y: 460, kind: 'snack',   content: 'salmon' },
      { x: 120, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 300, kind: 'snack',   content: 'salmon' },
      { x: 120, y: 460, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 460, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 620, kind: 'power',   content: 'slow' },
      { x: 538, y: 620, kind: 'power',   content: 'magnet' },
      { x: 183, y: 583, kind: 'veggie',  content: 'celery' },
      { x: 532, y: 364, kind: 'veggie',  content: 'broccoli' },
      { x: 419, y: 535, kind: 'snack',   content: 'salmon' },
      { x: 70, y: 534, kind: 'snack',   content: 'salmon' },
      { x: 176, y: 521, kind: 'power',   content: 'slow' },
      { x: 357, y: 532, kind: 'snack',   content: 'tuna' },
      { x: 516, y: 246, kind: 'veggie',  content: 'celery' },
      { x: 476, y: 577, kind: 'snack',   content: 'salmon' },
      { x: 529, y: 532, kind: 'snack',   content: 'salmon' },
      { x: 520, y: 180, kind: 'veggie',  content: 'celery' },
      { x: 243, y: 524, kind: 'power',   content: 'slow' },
      { x: 66, y: 348, kind: 'veggie',  content: 'celery' },
      { x: 124, y: 241, kind: 'veggie',  content: 'broccoli' },
      { x: 123, y: 576, kind: 'veggie',  content: 'celery' },
      { x: 64, y: 290, kind: 'power',   content: 'slow' },
      { x: 178, y: 421, kind: 'snack',   content: 'salmon' },
    ],
  },
  {
    name: 'Honeycomb',
    balls: 32,
    par: 25,
    goal: 165,
    vacuum: true,
    barrels: [
      { x: 170, y: 260, kind: 'snack',   content: 'tuna' },
      { x: 115, y: 295, kind: 'snack',   content: 'salmon' },
      { x: 225, y: 295, kind: 'snack',   content: 'salmon' },
      { x: 115, y: 365, kind: 'snack',   content: 'salmon' },
      { x: 225, y: 365, kind: 'snack',   content: 'salmon' },
      { x: 170, y: 400, kind: 'snack',   content: 'tuna' },
      { x: 430, y: 260, kind: 'snack',   content: 'tuna' },
      { x: 375, y: 295, kind: 'snack',   content: 'salmon' },
      { x: 485, y: 295, kind: 'snack',   content: 'salmon' },
      { x: 375, y: 365, kind: 'snack',   content: 'salmon' },
      { x: 485, y: 365, kind: 'snack',   content: 'salmon' },
      { x: 430, y: 400, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 330, kind: 'veggie',  content: 'broccoli' },
      { x: 300, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 620, kind: 'power',   content: 'multi' },
      { x: 538, y: 620, kind: 'power',   content: 'wide' },
      { x: 128, y: 475, kind: 'snack',   content: 'tuna' },
      { x: 62, y: 473, kind: 'snack',   content: 'tuna' },
      { x: 406, y: 531, kind: 'snack',   content: 'salmon' },
      { x: 238, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 469, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 518, y: 464, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 243, kind: 'snack',   content: 'salmon' },
      { x: 185, y: 586, kind: 'power',   content: 'wide' },
      { x: 127, y: 576, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 589, kind: 'snack',   content: 'salmon' },
      { x: 286, y: 246, kind: 'snack',   content: 'salmon' },
      { x: 521, y: 185, kind: 'snack',   content: 'salmon' },
      { x: 176, y: 186, kind: 'snack',   content: 'salmon' },
      { x: 288, y: 416, kind: 'snack',   content: 'salmon' },
      { x: 172, y: 521, kind: 'snack',   content: 'salmon' },
      { x: 478, y: 595, kind: 'snack',   content: 'tuna' },
      { x: 72, y: 408, kind: 'power',   content: 'wide' },
      { x: 400, y: 588, kind: 'snack',   content: 'salmon' },
    ],
  },
  {
    name: 'Veggie Minefield',
    balls: 32,
    par: 25,
    goal: 94,
    barrels: [
      { x: 100, y: 200, kind: 'snack',   content: 'salmon' },
      { x: 220, y: 200, kind: 'veggie',  content: 'broccoli' },
      { x: 340, y: 200, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 200, kind: 'veggie',  content: 'broccoli' },
      { x: 160, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 300, kind: 'veggie',  content: 'celery' },
      { x: 440, y: 300, kind: 'snack',   content: 'tuna' },
      { x: 100, y: 400, kind: 'veggie',  content: 'broccoli' },
      { x: 220, y: 400, kind: 'snack',   content: 'salmon' },
      { x: 340, y: 400, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 400, kind: 'veggie',  content: 'broccoli' },
      { x: 160, y: 500, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 500, kind: 'snack',   content: 'tuna' },
      { x: 440, y: 500, kind: 'veggie',  content: 'celery' },
      { x: 220, y: 600, kind: 'power',   content: 'magnet' },
      { x: 380, y: 600, kind: 'power',   content: 'slow' },
      { x: 467, y: 580, kind: 'snack',   content: 'tuna' },
      { x: 362, y: 470, kind: 'veggie',  content: 'broccoli' },
      { x: 360, y: 305, kind: 'power',   content: 'magnet' },
      { x: 304, y: 596, kind: 'snack',   content: 'salmon' },
      { x: 527, y: 292, kind: 'power',   content: 'magnet' },
      { x: 292, y: 239, kind: 'snack',   content: 'tuna' },
      { x: 241, y: 470, kind: 'veggie',  content: 'broccoli' },
      { x: 242, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 415, y: 245, kind: 'snack',   content: 'tuna' },
      { x: 227, y: 290, kind: 'veggie',  content: 'celery' },
      { x: 114, y: 590, kind: 'snack',   content: 'salmon' },
      { x: 528, y: 234, kind: 'snack',   content: 'salmon' },
      { x: 518, y: 465, kind: 'veggie',  content: 'broccoli' },
      { x: 518, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 355, y: 535, kind: 'snack',   content: 'tuna' },
      { x: 68, y: 536, kind: 'veggie',  content: 'broccoli' },
      { x: 119, y: 460, kind: 'veggie',  content: 'celery' },
      { x: 536, y: 407, kind: 'veggie',  content: 'celery' },
    ],
  },
  {
    name: 'Power Tower',
    balls: 29,
    par: 22,
    goal: 161,
    barrels: [
      { x: 300, y: 200, kind: 'power',   content: 'multi' },
      { x: 300, y: 320, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 440, kind: 'power',   content: 'wide' },
      { x: 300, y: 560, kind: 'snack',   content: 'tuna' },
      { x: 140, y: 260, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 140, y: 500, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 260, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 460, y: 500, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 320, kind: 'snack',   content: 'salmon' },
      { x: 220, y: 620, kind: 'snack',   content: 'salmon' },
      { x: 380, y: 620, kind: 'snack',   content: 'salmon' },
      { x: 62, y: 620, kind: 'power',   content: 'slow' },
      { x: 538, y: 620, kind: 'power',   content: 'magnet' },
      { x: 238, y: 405, kind: 'snack',   content: 'tuna' },
      { x: 114, y: 594, kind: 'power',   content: 'slow' },
      { x: 182, y: 186, kind: 'power',   content: 'multi' },
      { x: 464, y: 576, kind: 'snack',   content: 'tuna' },
      { x: 402, y: 521, kind: 'snack',   content: 'tuna' },
      { x: 347, y: 404, kind: 'power',   content: 'slow' },
      { x: 346, y: 524, kind: 'snack',   content: 'salmon' },
      { x: 232, y: 476, kind: 'snack',   content: 'salmon' },
      { x: 116, y: 186, kind: 'snack',   content: 'salmon' },
      { x: 532, y: 241, kind: 'snack',   content: 'salmon' },
      { x: 170, y: 584, kind: 'snack',   content: 'salmon' },
      { x: 243, y: 237, kind: 'snack',   content: 'salmon' },
      { x: 519, y: 463, kind: 'snack',   content: 'salmon' },
      { x: 351, y: 344, kind: 'power',   content: 'slow' },
      { x: 401, y: 241, kind: 'snack',   content: 'salmon' },
      { x: 231, y: 302, kind: 'snack',   content: 'salmon' },
      { x: 407, y: 360, kind: 'snack',   content: 'salmon' },
      { x: 67, y: 409, kind: 'snack',   content: 'salmon' },
      { x: 342, y: 245, kind: 'snack',   content: 'salmon' },
      { x: 243, y: 532, kind: 'snack',   content: 'salmon' },
      { x: 470, y: 182, kind: 'snack',   content: 'salmon' },
      { x: 526, y: 523, kind: 'snack',   content: 'tuna' },
    ],
  },
  {
    name: 'The Grand Feast',
    balls: 40,
    par: 31,
    goal: 143,
    vacuum: true,
    barrels: [
      { x: 62, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 300, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 420, y: 180, kind: 'snack',   content: 'salmon' },
      { x: 538, y: 180, kind: 'snack',   content: 'tuna' },
      { x: 120, y: 280, kind: 'snack',   content: 'salmon' },
      { x: 240, y: 280, kind: 'veggie',  content: 'broccoli' },
      { x: 360, y: 280, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 280, kind: 'veggie',  content: 'broccoli' },
      { x: 62, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 180, y: 380, kind: 'snack',   content: 'tuna' },
      { x: 300, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 420, y: 380, kind: 'snack',   content: 'tuna' },
      { x: 538, y: 380, kind: 'snack',   content: 'salmon' },
      { x: 120, y: 480, kind: 'veggie',  content: 'broccoli' },
      { x: 240, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 360, y: 480, kind: 'snack',   content: 'salmon' },
      { x: 480, y: 480, kind: 'snack',   content: 'tuna' },
      { x: 180, y: 580, kind: 'power',   content: 'multi' },
      { x: 300, y: 580, kind: 'power',   content: 'wide' },
      { x: 420, y: 580, kind: 'power',   content: 'slow' },
      { x: 62, y: 620, kind: 'power',   content: 'magnet' },
      { x: 67, y: 531, kind: 'snack',   content: 'tuna' },
      { x: 116, y: 420, kind: 'snack',   content: 'tuna' },
      { x: 476, y: 581, kind: 'snack',   content: 'salmon' },
      { x: 284, y: 240, kind: 'veggie',  content: 'broccoli' },
      { x: 296, y: 468, kind: 'snack',   content: 'salmon' },
      { x: 362, y: 347, kind: 'power',   content: 'magnet' },
      { x: 118, y: 580, kind: 'power',   content: 'wide' },
      { x: 400, y: 527, kind: 'snack',   content: 'salmon' },
      { x: 526, y: 243, kind: 'snack',   content: 'tuna' },
      { x: 298, y: 297, kind: 'snack',   content: 'tuna' },
      { x: 243, y: 537, kind: 'power',   content: 'wide' },
      { x: 415, y: 236, kind: 'power',   content: 'magnet' },
      { x: 349, y: 420, kind: 'snack',   content: 'salmon' },
      { x: 239, y: 358, kind: 'veggie',  content: 'broccoli' },
      { x: 520, y: 520, kind: 'power',   content: 'slow' },
      { x: 245, y: 416, kind: 'snack',   content: 'salmon' },
    ],
  },
];
