'use strict';
/* Level data. kind: 'snack' | 'veggie' | 'power'. content keys must exist in CONTENT (barrels.js).
   Levels 2-6 layouts drafted by qwen-fast sub-agent, validated headless (bounds, spacing, calorie budget). */

const LEVELS = [
  {
    name: 'First Breakfast',
    balls: 37,
    par: 28,
    goal: 37,
    r: 10,
    barrels: [
      { x: 270, y: 296, kind: 'veggie', content: 'celery' },
      { x: 330, y: 296, kind: 'veggie', content: 'celery' },
      { x: 240, y: 296, kind: 'snack',  content: 'kibble', armor: true },
      { x: 360, y: 296, kind: 'snack',  content: 'kibble' },
      { x: 285, y: 322, kind: 'snack',  content: 'salmon' },
      { x: 315, y: 322, kind: 'snack',  content: 'salmon' },
      { x: 225, y: 322, kind: 'veggie', content: 'broccoli' },
      { x: 375, y: 322, kind: 'veggie', content: 'broccoli' },
      { x: 195, y: 322, kind: 'empty',  content: null  },
      { x: 405, y: 322, kind: 'empty',  content: null  },
      { x: 240, y: 348, kind: 'snack',  content: 'kibble' },
      { x: 360, y: 348, kind: 'snack',  content: 'kibble' },
      { x: 210, y: 348, kind: 'empty',  content: null  },
      { x: 390, y: 348, kind: 'empty',  content: null  },
      { x: 255, y: 374, kind: 'empty',  content: null  },
      { x: 345, y: 374, kind: 'empty',  content: null  },
      { x: 225, y: 374, kind: 'empty',  content: null  },
      { x: 375, y: 374, kind: 'empty',  content: null  },
      { x: 195, y: 374, kind: 'empty',  content: null  },
      { x: 405, y: 374, kind: 'empty',  content: null  },
      { x: 300, y: 400, kind: 'snack',  content: 'salmon' },
      { x: 240, y: 400, kind: 'veggie', content: 'celery' },
      { x: 360, y: 400, kind: 'veggie', content: 'celery' },
      { x: 210, y: 400, kind: 'empty',  content: null  },
      { x: 390, y: 400, kind: 'empty',  content: null  },
      { x: 255, y: 426, kind: 'snack',  content: 'kibble' },
      { x: 345, y: 426, kind: 'snack',  content: 'kibble' },
      { x: 225, y: 426, kind: 'empty',  content: null  },
      { x: 375, y: 426, kind: 'empty',  content: null  },
      { x: 195, y: 426, kind: 'snack',  content: 'salmon' },
      { x: 405, y: 426, kind: 'snack',  content: 'salmon' },
      { x: 165, y: 426, kind: 'empty',  content: null  },
      { x: 435, y: 426, kind: 'empty',  content: null  },
      { x: 300, y: 452, kind: 'empty',  content: null  },
      { x: 270, y: 452, kind: 'snack',  content: 'salmon' },
      { x: 330, y: 452, kind: 'snack',  content: 'salmon' },
      { x: 240, y: 452, kind: 'empty',  content: null  },
      { x: 360, y: 452, kind: 'empty',  content: null  },
      { x: 210, y: 452, kind: 'empty',  content: null  },
      { x: 390, y: 452, kind: 'empty',  content: null  },
      { x: 255, y: 478, kind: 'power',  content: 'split' },
      { x: 345, y: 478, kind: 'power',  content: 'split' },
      { x: 165, y: 478, kind: 'snack',  content: 'tuna' },
      { x: 435, y: 478, kind: 'snack',  content: 'tuna' },
      { x: 300, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 270, y: 504, kind: 'empty',  content: null  },
      { x: 330, y: 504, kind: 'empty',  content: null  },
      { x: 240, y: 504, kind: 'empty',  content: null  },
      { x: 360, y: 504, kind: 'empty',  content: null  },
      { x: 210, y: 504, kind: 'snack',  content: 'tuna' },
      { x: 390, y: 504, kind: 'snack',  content: 'tuna' },
      { x: 180, y: 504, kind: 'empty',  content: null  },
      { x: 420, y: 504, kind: 'empty',  content: null  },
      { x: 285, y: 530, kind: 'snack',  content: 'tuna' },
      { x: 315, y: 530, kind: 'snack',  content: 'tuna' },
      { x: 255, y: 530, kind: 'empty',  content: null  },
      { x: 345, y: 530, kind: 'empty',  content: null  },
      { x: 225, y: 530, kind: 'snack',  content: 'kibble' },
      { x: 375, y: 530, kind: 'snack',  content: 'kibble' },
      { x: 165, y: 530, kind: 'empty',  content: null  },
      { x: 435, y: 530, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Pyramid Pounce',
    balls: 39,
    par: 29,
    goal: 52,
    r: 10,
    barrels: [
      { x: 300, y: 192, kind: 'veggie', content: 'broccoli' },
      { x: 285, y: 218, kind: 'empty',  content: null  },
      { x: 315, y: 218, kind: 'empty',  content: null  },
      { x: 300, y: 244, kind: 'snack',  content: 'tuna' },
      { x: 255, y: 270, kind: 'snack',  content: 'tuna' },
      { x: 345, y: 270, kind: 'snack',  content: 'tuna' },
      { x: 240, y: 296, kind: 'veggie', content: 'celery' },
      { x: 360, y: 296, kind: 'veggie', content: 'celery' },
      { x: 210, y: 296, kind: 'snack',  content: 'salmon' },
      { x: 390, y: 296, kind: 'snack',  content: 'salmon', armor: true },
      { x: 285, y: 322, kind: 'empty',  content: null  },
      { x: 315, y: 322, kind: 'empty',  content: null  },
      { x: 255, y: 322, kind: 'snack',  content: 'tuna', armor: true },
      { x: 345, y: 322, kind: 'snack',  content: 'tuna' },
      { x: 225, y: 322, kind: 'empty',  content: null  },
      { x: 375, y: 322, kind: 'empty',  content: null  },
      { x: 165, y: 322, kind: 'snack',  content: 'tuna', armor: true },
      { x: 435, y: 322, kind: 'snack',  content: 'tuna' },
      { x: 180, y: 348, kind: 'empty',  content: null  },
      { x: 420, y: 348, kind: 'empty',  content: null  },
      { x: 285, y: 374, kind: 'veggie', content: 'celery' },
      { x: 315, y: 374, kind: 'veggie', content: 'celery' },
      { x: 255, y: 374, kind: 'empty',  content: null  },
      { x: 345, y: 374, kind: 'empty',  content: null  },
      { x: 225, y: 374, kind: 'snack',  content: 'tuna' },
      { x: 375, y: 374, kind: 'snack',  content: 'tuna', armor: true },
      { x: 195, y: 374, kind: 'snack',  content: 'tuna' },
      { x: 405, y: 374, kind: 'snack',  content: 'tuna' },
      { x: 165, y: 374, kind: 'empty',  content: null  },
      { x: 435, y: 374, kind: 'empty',  content: null  },
      { x: 270, y: 400, kind: 'empty',  content: null  },
      { x: 330, y: 400, kind: 'empty',  content: null  },
      { x: 240, y: 400, kind: 'power',  content: 'multi' },
      { x: 360, y: 400, kind: 'power',  content: 'multi' },
      { x: 210, y: 400, kind: 'veggie', content: 'celery' },
      { x: 390, y: 400, kind: 'veggie', content: 'celery' },
      { x: 180, y: 400, kind: 'snack',  content: 'tuna' },
      { x: 420, y: 400, kind: 'snack',  content: 'tuna' },
      { x: 150, y: 400, kind: 'veggie', content: 'broccoli' },
      { x: 450, y: 400, kind: 'veggie', content: 'broccoli' },
      { x: 165, y: 426, kind: 'empty',  content: null  },
      { x: 435, y: 426, kind: 'empty',  content: null  },
      { x: 270, y: 452, kind: 'empty',  content: null  },
      { x: 330, y: 452, kind: 'empty',  content: null  },
      { x: 210, y: 452, kind: 'empty',  content: null  },
      { x: 390, y: 452, kind: 'empty',  content: null  },
      { x: 255, y: 478, kind: 'power',  content: 'split' },
      { x: 345, y: 478, kind: 'power',  content: 'split' },
      { x: 195, y: 478, kind: 'empty',  content: null  },
      { x: 405, y: 478, kind: 'empty',  content: null  },
      { x: 165, y: 478, kind: 'empty',  content: null  },
      { x: 435, y: 478, kind: 'empty',  content: null  },
      { x: 240, y: 504, kind: 'empty',  content: null  },
      { x: 360, y: 504, kind: 'empty',  content: null  },
      { x: 210, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 390, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 180, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 420, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 285, y: 530, kind: 'empty',  content: null  },
      { x: 315, y: 530, kind: 'empty',  content: null  },
      { x: 255, y: 530, kind: 'empty',  content: null  },
      { x: 345, y: 530, kind: 'empty',  content: null  },
      { x: 300, y: 556, kind: 'snack',  content: 'salmon' },
      { x: 240, y: 556, kind: 'empty',  content: null  },
      { x: 360, y: 556, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Starstruck',
    balls: 43,
    par: 32,
    goal: 61,
    r: 10,
    barrels: [
      { x: 300, y: 192, kind: 'veggie', content: 'broccoli' },
      { x: 285, y: 218, kind: 'empty',  content: null  },
      { x: 315, y: 218, kind: 'empty',  content: null  },
      { x: 300, y: 244, kind: 'snack',  content: 'kibble' },
      { x: 285, y: 270, kind: 'empty',  content: null  },
      { x: 315, y: 270, kind: 'empty',  content: null  },
      { x: 270, y: 296, kind: 'snack',  content: 'salmon' },
      { x: 330, y: 296, kind: 'snack',  content: 'salmon' },
      { x: 285, y: 322, kind: 'empty',  content: null  },
      { x: 315, y: 322, kind: 'empty',  content: null  },
      { x: 255, y: 322, kind: 'empty',  content: null  },
      { x: 345, y: 322, kind: 'empty',  content: null  },
      { x: 225, y: 322, kind: 'empty',  content: null  },
      { x: 375, y: 322, kind: 'empty',  content: null  },
      { x: 165, y: 322, kind: 'snack',  content: 'kibble' },
      { x: 435, y: 322, kind: 'snack',  content: 'kibble' },
      { x: 135, y: 322, kind: 'empty',  content: null  },
      { x: 465, y: 322, kind: 'empty',  content: null  },
      { x: 300, y: 348, kind: 'veggie', content: 'broccoli' },
      { x: 270, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 330, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 210, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 390, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 120, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 480, y: 348, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 348, kind: 'empty',  content: null  },
      { x: 510, y: 348, kind: 'empty',  content: null  },
      { x: 285, y: 374, kind: 'snack',  content: 'salmon' },
      { x: 315, y: 374, kind: 'snack',  content: 'salmon' },
      { x: 195, y: 374, kind: 'empty',  content: null  },
      { x: 405, y: 374, kind: 'empty',  content: null  },
      { x: 300, y: 400, kind: 'snack',  content: 'kibble', armor: true },
      { x: 270, y: 400, kind: 'snack',  content: 'tuna' },
      { x: 330, y: 400, kind: 'snack',  content: 'tuna' },
      { x: 210, y: 400, kind: 'empty',  content: null  },
      { x: 390, y: 400, kind: 'empty',  content: null  },
      { x: 180, y: 400, kind: 'snack',  content: 'salmon' },
      { x: 420, y: 400, kind: 'snack',  content: 'salmon' },
      { x: 150, y: 400, kind: 'empty',  content: null  },
      { x: 450, y: 400, kind: 'empty',  content: null  },
      { x: 255, y: 426, kind: 'snack',  content: 'tuna' },
      { x: 345, y: 426, kind: 'snack',  content: 'tuna' },
      { x: 225, y: 426, kind: 'empty',  content: null  },
      { x: 375, y: 426, kind: 'empty',  content: null  },
      { x: 195, y: 426, kind: 'empty',  content: null  },
      { x: 405, y: 426, kind: 'empty',  content: null  },
      { x: 300, y: 452, kind: 'veggie', content: 'broccoli' },
      { x: 270, y: 452, kind: 'snack',  content: 'salmon' },
      { x: 330, y: 452, kind: 'snack',  content: 'salmon' },
      { x: 240, y: 452, kind: 'empty',  content: null  },
      { x: 360, y: 452, kind: 'empty',  content: null  },
      { x: 210, y: 452, kind: 'power',  content: 'split' },
      { x: 390, y: 452, kind: 'power',  content: 'split' },
      { x: 255, y: 478, kind: 'empty',  content: null  },
      { x: 345, y: 478, kind: 'empty',  content: null  },
      { x: 225, y: 478, kind: 'snack',  content: 'salmon' },
      { x: 375, y: 478, kind: 'snack',  content: 'salmon', armor: true },
      { x: 195, y: 478, kind: 'snack',  content: 'salmon' },
      { x: 405, y: 478, kind: 'snack',  content: 'salmon' },
      { x: 300, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 240, y: 504, kind: 'empty',  content: null  },
      { x: 360, y: 504, kind: 'empty',  content: null  },
      { x: 180, y: 504, kind: 'empty',  content: null  },
      { x: 420, y: 504, kind: 'empty',  content: null  },
      { x: 255, y: 530, kind: 'empty',  content: null  },
      { x: 345, y: 530, kind: 'empty',  content: null  },
      { x: 225, y: 530, kind: 'empty',  content: null  },
      { x: 375, y: 530, kind: 'empty',  content: null  },
      { x: 195, y: 530, kind: 'snack',  content: 'kibble' },
      { x: 405, y: 530, kind: 'snack',  content: 'kibble' },
      { x: 210, y: 556, kind: 'snack',  content: 'salmon' },
      { x: 390, y: 556, kind: 'snack',  content: 'salmon', armor: true },
    ],
  },
  {
    name: 'Heartbreaker',
    balls: 47,
    par: 35,
    goal: 43,
    r: 10,
    barrels: [
      { x: 240, y: 140, kind: 'snack',  content: 'kibble' },
      { x: 360, y: 140, kind: 'snack',  content: 'kibble' },
      { x: 180, y: 140, kind: 'veggie', content: 'celery' },
      { x: 420, y: 140, kind: 'veggie', content: 'celery' },
      { x: 255, y: 166, kind: 'empty',  content: null  },
      { x: 345, y: 166, kind: 'empty',  content: null  },
      { x: 240, y: 192, kind: 'snack',  content: 'tuna' },
      { x: 360, y: 192, kind: 'snack',  content: 'tuna' },
      { x: 120, y: 192, kind: 'veggie', content: 'celery' },
      { x: 480, y: 192, kind: 'veggie', content: 'celery' },
      { x: 225, y: 218, kind: 'empty',  content: null  },
      { x: 375, y: 218, kind: 'empty',  content: null  },
      { x: 195, y: 218, kind: 'empty',  content: null  },
      { x: 405, y: 218, kind: 'empty',  content: null  },
      { x: 135, y: 218, kind: 'empty',  content: null  },
      { x: 465, y: 218, kind: 'empty',  content: null  },
      { x: 75, y: 218, kind: 'empty',  content: null  },
      { x: 525, y: 218, kind: 'empty',  content: null  },
      { x: 60, y: 244, kind: 'snack',  content: 'salmon' },
      { x: 540, y: 244, kind: 'snack',  content: 'salmon' },
      { x: 105, y: 270, kind: 'snack',  content: 'tuna' },
      { x: 495, y: 270, kind: 'snack',  content: 'tuna' },
      { x: 270, y: 296, kind: 'power',  content: 'magnet' },
      { x: 330, y: 296, kind: 'power',  content: 'magnet' },
      { x: 120, y: 296, kind: 'veggie', content: 'celery' },
      { x: 480, y: 296, kind: 'veggie', content: 'celery' },
      { x: 90, y: 296, kind: 'empty',  content: null  },
      { x: 510, y: 296, kind: 'empty',  content: null  },
      { x: 285, y: 322, kind: 'snack',  content: 'salmon' },
      { x: 315, y: 322, kind: 'snack',  content: 'salmon' },
      { x: 195, y: 322, kind: 'empty',  content: null  },
      { x: 405, y: 322, kind: 'empty',  content: null  },
      { x: 135, y: 322, kind: 'snack',  content: 'tuna' },
      { x: 465, y: 322, kind: 'snack',  content: 'tuna' },
      { x: 75, y: 322, kind: 'empty',  content: null  },
      { x: 525, y: 322, kind: 'empty',  content: null  },
      { x: 300, y: 348, kind: 'snack',  content: 'salmon' },
      { x: 270, y: 348, kind: 'snack',  content: 'salmon' },
      { x: 330, y: 348, kind: 'snack',  content: 'salmon' },
      { x: 180, y: 348, kind: 'veggie', content: 'broccoli' },
      { x: 420, y: 348, kind: 'veggie', content: 'broccoli' },
      { x: 255, y: 374, kind: 'empty',  content: null  },
      { x: 345, y: 374, kind: 'empty',  content: null  },
      { x: 225, y: 374, kind: 'snack',  content: 'kibble' },
      { x: 375, y: 374, kind: 'snack',  content: 'kibble', armor: true },
      { x: 105, y: 374, kind: 'empty',  content: null  },
      { x: 495, y: 374, kind: 'empty',  content: null  },
      { x: 90, y: 400, kind: 'empty',  content: null  },
      { x: 510, y: 400, kind: 'empty',  content: null  },
      { x: 60, y: 400, kind: 'empty',  content: null  },
      { x: 540, y: 400, kind: 'empty',  content: null  },
      { x: 285, y: 426, kind: 'empty',  content: null  },
      { x: 315, y: 426, kind: 'empty',  content: null  },
      { x: 75, y: 426, kind: 'veggie', content: 'broccoli' },
      { x: 525, y: 426, kind: 'veggie', content: 'broccoli' },
      { x: 240, y: 452, kind: 'veggie', content: 'broccoli' },
      { x: 360, y: 452, kind: 'veggie', content: 'broccoli' },
      { x: 225, y: 478, kind: 'empty',  content: null  },
      { x: 375, y: 478, kind: 'empty',  content: null  },
      { x: 300, y: 504, kind: 'snack',  content: 'tuna' },
      { x: 180, y: 504, kind: 'empty',  content: null  },
      { x: 420, y: 504, kind: 'empty',  content: null  },
      { x: 255, y: 530, kind: 'empty',  content: null  },
      { x: 345, y: 530, kind: 'empty',  content: null  },
      { x: 225, y: 530, kind: 'snack',  content: 'salmon' },
      { x: 375, y: 530, kind: 'snack',  content: 'salmon', armor: true },
      { x: 300, y: 556, kind: 'power',  content: 'split' },
      { x: 270, y: 556, kind: 'empty',  content: null  },
      { x: 330, y: 556, kind: 'empty',  content: null  },
      { x: 210, y: 556, kind: 'empty',  content: null  },
      { x: 390, y: 556, kind: 'empty',  content: null  },
      { x: 255, y: 582, kind: 'veggie', content: 'broccoli' },
      { x: 345, y: 582, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 608, kind: 'empty',  content: null  },
      { x: 270, y: 608, kind: 'snack',  content: 'salmon' },
      { x: 330, y: 608, kind: 'snack',  content: 'salmon', armor: true },
      { x: 285, y: 634, kind: 'empty',  content: null  },
      { x: 315, y: 634, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Smiley Face',
    balls: 50,
    par: 38,
    goal: 67,
    r: 10,
    barrels: [
      { x: 244, y: 188, kind: 'empty',  content: null  },
      { x: 356, y: 188, kind: 'empty',  content: null  },
      { x: 258, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 342, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 300, y: 237, kind: 'snack',  content: 'salmon' },
      { x: 272, y: 237, kind: 'empty',  content: null  },
      { x: 328, y: 237, kind: 'empty',  content: null  },
      { x: 244, y: 237, kind: 'empty',  content: null  },
      { x: 356, y: 237, kind: 'empty',  content: null  },
      { x: 286, y: 261, kind: 'snack',  content: 'kibble' },
      { x: 314, y: 261, kind: 'snack',  content: 'kibble' },
      { x: 118, y: 261, kind: 'empty',  content: null  },
      { x: 482, y: 261, kind: 'empty',  content: null  },
      { x: 188, y: 286, kind: 'veggie', content: 'celery' },
      { x: 412, y: 286, kind: 'veggie', content: 'celery' },
      { x: 258, y: 310, kind: 'empty',  content: null  },
      { x: 342, y: 310, kind: 'empty',  content: null  },
      { x: 174, y: 310, kind: 'empty',  content: null  },
      { x: 426, y: 310, kind: 'empty',  content: null  },
      { x: 146, y: 310, kind: 'empty',  content: null  },
      { x: 454, y: 310, kind: 'empty',  content: null  },
      { x: 90, y: 310, kind: 'empty',  content: null  },
      { x: 510, y: 310, kind: 'empty',  content: null  },
      { x: 300, y: 334, kind: 'snack',  content: 'salmon', armor: true },
      { x: 272, y: 334, kind: 'snack',  content: 'salmon' },
      { x: 328, y: 334, kind: 'snack',  content: 'salmon' },
      { x: 132, y: 334, kind: 'snack',  content: 'salmon' },
      { x: 468, y: 334, kind: 'snack',  content: 'salmon', armor: true },
      { x: 286, y: 358, kind: 'empty',  content: null  },
      { x: 314, y: 358, kind: 'empty',  content: null  },
      { x: 90, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 510, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 104, y: 382, kind: 'empty',  content: null  },
      { x: 496, y: 382, kind: 'empty',  content: null  },
      { x: 286, y: 407, kind: 'empty',  content: null  },
      { x: 314, y: 407, kind: 'empty',  content: null  },
      { x: 258, y: 407, kind: 'empty',  content: null  },
      { x: 342, y: 407, kind: 'empty',  content: null  },
      { x: 118, y: 407, kind: 'empty',  content: null  },
      { x: 482, y: 407, kind: 'empty',  content: null  },
      { x: 300, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 431, kind: 'empty',  content: null  },
      { x: 328, y: 431, kind: 'empty',  content: null  },
      { x: 244, y: 431, kind: 'empty',  content: null  },
      { x: 356, y: 431, kind: 'empty',  content: null  },
      { x: 188, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 412, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 468, y: 431, kind: 'snack',  content: 'salmon', armor: true },
      { x: 76, y: 431, kind: 'empty',  content: null  },
      { x: 524, y: 431, kind: 'empty',  content: null  },
      { x: 286, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 314, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 455, kind: 'veggie', content: 'celery' },
      { x: 510, y: 455, kind: 'veggie', content: 'celery' },
      { x: 300, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 244, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 356, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 160, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 440, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 480, kind: 'power',  content: 'split' },
      { x: 468, y: 480, kind: 'power',  content: 'split' },
      { x: 104, y: 480, kind: 'empty',  content: null  },
      { x: 496, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 314, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 146, y: 504, kind: 'empty',  content: null  },
      { x: 454, y: 504, kind: 'empty',  content: null  },
      { x: 118, y: 504, kind: 'veggie', content: 'celery' },
      { x: 482, y: 504, kind: 'veggie', content: 'celery' },
      { x: 244, y: 528, kind: 'empty',  content: null  },
      { x: 356, y: 528, kind: 'empty',  content: null  },
      { x: 160, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 440, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 104, y: 528, kind: 'snack',  content: 'tuna' },
      { x: 496, y: 528, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 576, kind: 'snack',  content: 'salmon', armor: true },
      { x: 356, y: 576, kind: 'snack',  content: 'salmon' },
      { x: 258, y: 601, kind: 'empty',  content: null  },
      { x: 342, y: 601, kind: 'empty',  content: null  },
      { x: 230, y: 601, kind: 'snack',  content: 'tuna' },
      { x: 370, y: 601, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 625, kind: 'empty',  content: null  },
      { x: 328, y: 625, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Diagonal Dash',
    balls: 53,
    par: 40,
    goal: 57,
    r: 10,
    vacuum: true,
    barrels: [
      { x: 272, y: 188, kind: 'empty',  content: null  },
      { x: 328, y: 188, kind: 'empty',  content: null  },
      { x: 188, y: 188, kind: 'empty',  content: null  },
      { x: 412, y: 188, kind: 'empty',  content: null  },
      { x: 76, y: 188, kind: 'empty',  content: null  },
      { x: 524, y: 188, kind: 'empty',  content: null  },
      { x: 202, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 398, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 213, kind: 'empty',  content: null  },
      { x: 510, y: 213, kind: 'empty',  content: null  },
      { x: 300, y: 237, kind: 'snack',  content: 'tuna', armor: true },
      { x: 188, y: 237, kind: 'empty',  content: null  },
      { x: 412, y: 237, kind: 'empty',  content: null  },
      { x: 104, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 496, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 76, y: 237, kind: 'snack',  content: 'salmon' },
      { x: 524, y: 237, kind: 'snack',  content: 'salmon' },
      { x: 286, y: 261, kind: 'empty',  content: null  },
      { x: 314, y: 261, kind: 'empty',  content: null  },
      { x: 300, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 188, y: 286, kind: 'empty',  content: null  },
      { x: 412, y: 286, kind: 'empty',  content: null  },
      { x: 202, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 398, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 174, y: 310, kind: 'power',  content: 'split' },
      { x: 426, y: 310, kind: 'power',  content: 'split' },
      { x: 272, y: 334, kind: 'empty',  content: null  },
      { x: 328, y: 334, kind: 'empty',  content: null  },
      { x: 188, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 412, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 286, y: 358, kind: 'empty',  content: null  },
      { x: 314, y: 358, kind: 'empty',  content: null  },
      { x: 202, y: 358, kind: 'snack',  content: 'kibble' },
      { x: 398, y: 358, kind: 'snack',  content: 'kibble', armor: true },
      { x: 174, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 426, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 300, y: 382, kind: 'empty',  content: null  },
      { x: 272, y: 382, kind: 'empty',  content: null  },
      { x: 328, y: 382, kind: 'empty',  content: null  },
      { x: 286, y: 407, kind: 'empty',  content: null  },
      { x: 314, y: 407, kind: 'empty',  content: null  },
      { x: 202, y: 407, kind: 'empty',  content: null  },
      { x: 398, y: 407, kind: 'empty',  content: null  },
      { x: 174, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 426, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 90, y: 407, kind: 'empty',  content: null  },
      { x: 510, y: 407, kind: 'empty',  content: null  },
      { x: 300, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 76, y: 431, kind: 'veggie', content: 'broccoli' },
      { x: 524, y: 431, kind: 'veggie', content: 'broccoli' },
      { x: 272, y: 480, kind: 'veggie', content: 'celery' },
      { x: 328, y: 480, kind: 'veggie', content: 'celery' },
      { x: 188, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 412, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 104, y: 480, kind: 'empty',  content: null  },
      { x: 496, y: 480, kind: 'empty',  content: null  },
      { x: 76, y: 480, kind: 'empty',  content: null  },
      { x: 524, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'empty',  content: null  },
      { x: 314, y: 504, kind: 'empty',  content: null  },
      { x: 202, y: 504, kind: 'empty',  content: null  },
      { x: 398, y: 504, kind: 'empty',  content: null  },
      { x: 174, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 426, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 528, kind: 'snack',  content: 'tuna' },
      { x: 188, y: 528, kind: 'veggie', content: 'broccoli' },
      { x: 412, y: 528, kind: 'veggie', content: 'broccoli' },
      { x: 104, y: 528, kind: 'veggie', content: 'celery' },
      { x: 496, y: 528, kind: 'veggie', content: 'celery' },
      { x: 76, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 524, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 286, y: 552, kind: 'empty',  content: null  },
      { x: 314, y: 552, kind: 'empty',  content: null  },
      { x: 174, y: 552, kind: 'snack',  content: 'kibble' },
      { x: 426, y: 552, kind: 'snack',  content: 'kibble' },
      { x: 300, y: 576, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 576, kind: 'empty',  content: null  },
      { x: 328, y: 576, kind: 'empty',  content: null  },
      { x: 188, y: 576, kind: 'empty',  content: null  },
      { x: 412, y: 576, kind: 'empty',  content: null  },
      { x: 286, y: 601, kind: 'empty',  content: null  },
      { x: 314, y: 601, kind: 'empty',  content: null  },
      { x: 202, y: 601, kind: 'snack',  content: 'kibble' },
      { x: 398, y: 601, kind: 'snack',  content: 'kibble', armor: true },
      { x: 300, y: 625, kind: 'empty',  content: null  },
      { x: 272, y: 625, kind: 'snack',  content: 'tuna' },
      { x: 328, y: 625, kind: 'snack',  content: 'tuna' },
      { x: 76, y: 625, kind: 'snack',  content: 'salmon' },
      { x: 524, y: 625, kind: 'snack',  content: 'salmon' },
    ],
  },
  {
    name: 'Twin Peaks',
    balls: 58,
    par: 44,
    goal: 62,
    r: 10,
    barrels: [
      { x: 202, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 398, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 174, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 426, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 272, y: 286, kind: 'empty',  content: null  },
      { x: 328, y: 286, kind: 'empty',  content: null  },
      { x: 244, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 356, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 216, y: 286, kind: 'empty',  content: null  },
      { x: 384, y: 286, kind: 'empty',  content: null  },
      { x: 188, y: 286, kind: 'empty',  content: null  },
      { x: 412, y: 286, kind: 'empty',  content: null  },
      { x: 258, y: 310, kind: 'empty',  content: null  },
      { x: 342, y: 310, kind: 'empty',  content: null  },
      { x: 230, y: 310, kind: 'empty',  content: null  },
      { x: 370, y: 310, kind: 'empty',  content: null  },
      { x: 202, y: 310, kind: 'snack',  content: 'salmon' },
      { x: 398, y: 310, kind: 'snack',  content: 'salmon' },
      { x: 146, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 454, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 334, kind: 'power',  content: 'magnet' },
      { x: 272, y: 334, kind: 'empty',  content: null  },
      { x: 328, y: 334, kind: 'empty',  content: null  },
      { x: 160, y: 334, kind: 'power',  content: 'wide' },
      { x: 440, y: 334, kind: 'power',  content: 'wide' },
      { x: 104, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 496, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 286, y: 358, kind: 'empty',  content: null  },
      { x: 314, y: 358, kind: 'empty',  content: null  },
      { x: 230, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 370, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 202, y: 358, kind: 'empty',  content: null  },
      { x: 398, y: 358, kind: 'empty',  content: null  },
      { x: 174, y: 358, kind: 'veggie', content: 'celery' },
      { x: 426, y: 358, kind: 'veggie', content: 'celery' },
      { x: 146, y: 358, kind: 'empty',  content: null  },
      { x: 454, y: 358, kind: 'empty',  content: null  },
      { x: 118, y: 358, kind: 'snack',  content: 'salmon', armor: true },
      { x: 482, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 300, y: 382, kind: 'empty',  content: null  },
      { x: 244, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 356, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 216, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 384, y: 382, kind: 'snack',  content: 'salmon', armor: true },
      { x: 188, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 412, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 104, y: 382, kind: 'empty',  content: null  },
      { x: 496, y: 382, kind: 'empty',  content: null  },
      { x: 286, y: 407, kind: 'empty',  content: null  },
      { x: 314, y: 407, kind: 'empty',  content: null  },
      { x: 258, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 202, y: 407, kind: 'empty',  content: null  },
      { x: 398, y: 407, kind: 'empty',  content: null  },
      { x: 174, y: 407, kind: 'empty',  content: null  },
      { x: 426, y: 407, kind: 'empty',  content: null  },
      { x: 62, y: 407, kind: 'snack',  content: 'kibble' },
      { x: 538, y: 407, kind: 'snack',  content: 'kibble' },
      { x: 300, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 272, y: 431, kind: 'empty',  content: null  },
      { x: 328, y: 431, kind: 'empty',  content: null  },
      { x: 244, y: 431, kind: 'empty',  content: null  },
      { x: 356, y: 431, kind: 'empty',  content: null  },
      { x: 216, y: 431, kind: 'veggie', content: 'celery' },
      { x: 384, y: 431, kind: 'veggie', content: 'celery' },
      { x: 90, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 510, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 62, y: 455, kind: 'empty',  content: null  },
      { x: 538, y: 455, kind: 'empty',  content: null  },
      { x: 300, y: 480, kind: 'snack',  content: 'tuna', armor: true },
      { x: 272, y: 480, kind: 'empty',  content: null  },
      { x: 328, y: 480, kind: 'empty',  content: null  },
      { x: 244, y: 480, kind: 'empty',  content: null  },
      { x: 356, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'snack',  content: 'kibble', armor: true },
      { x: 314, y: 504, kind: 'snack',  content: 'kibble' },
      { x: 258, y: 504, kind: 'empty',  content: null  },
      { x: 342, y: 504, kind: 'empty',  content: null  },
      { x: 230, y: 504, kind: 'empty',  content: null  },
      { x: 370, y: 504, kind: 'empty',  content: null  },
      { x: 174, y: 504, kind: 'empty',  content: null  },
      { x: 426, y: 504, kind: 'empty',  content: null  },
      { x: 146, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 454, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 118, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 482, y: 504, kind: 'snack',  content: 'salmon' },
      { x: 90, y: 504, kind: 'empty',  content: null  },
      { x: 510, y: 504, kind: 'empty',  content: null  },
      { x: 272, y: 528, kind: 'empty',  content: null  },
      { x: 328, y: 528, kind: 'empty',  content: null  },
      { x: 244, y: 528, kind: 'empty',  content: null  },
      { x: 356, y: 528, kind: 'empty',  content: null  },
      { x: 132, y: 528, kind: 'power',  content: 'split' },
      { x: 468, y: 528, kind: 'power',  content: 'split' },
      { x: 202, y: 552, kind: 'snack',  content: 'tuna' },
      { x: 398, y: 552, kind: 'snack',  content: 'tuna' },
    ],
  },
  {
    name: 'The Gauntlet',
    balls: 59,
    par: 44,
    goal: 61,
    r: 10,
    barrels: [
      { x: 258, y: 164, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 164, kind: 'snack',  content: 'salmon', armor: true },
      { x: 230, y: 164, kind: 'empty',  content: null  },
      { x: 370, y: 164, kind: 'empty',  content: null  },
      { x: 300, y: 188, kind: 'empty',  content: null  },
      { x: 272, y: 188, kind: 'empty',  content: null  },
      { x: 328, y: 188, kind: 'empty',  content: null  },
      { x: 160, y: 188, kind: 'snack',  content: 'salmon' },
      { x: 440, y: 188, kind: 'snack',  content: 'salmon' },
      { x: 258, y: 213, kind: 'empty',  content: null  },
      { x: 342, y: 213, kind: 'empty',  content: null  },
      { x: 244, y: 237, kind: 'empty',  content: null  },
      { x: 356, y: 237, kind: 'empty',  content: null  },
      { x: 216, y: 237, kind: 'empty',  content: null  },
      { x: 384, y: 237, kind: 'empty',  content: null  },
      { x: 160, y: 237, kind: 'empty',  content: null  },
      { x: 440, y: 237, kind: 'empty',  content: null  },
      { x: 104, y: 237, kind: 'veggie', content: 'celery' },
      { x: 496, y: 237, kind: 'veggie', content: 'celery' },
      { x: 286, y: 261, kind: 'empty',  content: null  },
      { x: 314, y: 261, kind: 'empty',  content: null  },
      { x: 258, y: 261, kind: 'empty',  content: null  },
      { x: 342, y: 261, kind: 'empty',  content: null  },
      { x: 146, y: 261, kind: 'veggie', content: 'celery' },
      { x: 454, y: 261, kind: 'veggie', content: 'celery' },
      { x: 188, y: 286, kind: 'empty',  content: null  },
      { x: 412, y: 286, kind: 'empty',  content: null  },
      { x: 160, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 440, y: 286, kind: 'snack',  content: 'salmon', armor: true },
      { x: 132, y: 286, kind: 'snack',  content: 'tuna' },
      { x: 468, y: 286, kind: 'snack',  content: 'tuna' },
      { x: 104, y: 286, kind: 'snack',  content: 'tuna' },
      { x: 496, y: 286, kind: 'snack',  content: 'tuna' },
      { x: 76, y: 286, kind: 'empty',  content: null  },
      { x: 524, y: 286, kind: 'empty',  content: null  },
      { x: 118, y: 310, kind: 'empty',  content: null  },
      { x: 482, y: 310, kind: 'empty',  content: null  },
      { x: 188, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 412, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 160, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 440, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 334, kind: 'empty',  content: null  },
      { x: 468, y: 334, kind: 'empty',  content: null  },
      { x: 146, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 454, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 62, y: 358, kind: 'empty',  content: null  },
      { x: 538, y: 358, kind: 'empty',  content: null  },
      { x: 132, y: 382, kind: 'empty',  content: null  },
      { x: 468, y: 382, kind: 'empty',  content: null  },
      { x: 174, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 426, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 160, y: 431, kind: 'empty',  content: null  },
      { x: 440, y: 431, kind: 'empty',  content: null  },
      { x: 146, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 454, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 118, y: 455, kind: 'empty',  content: null  },
      { x: 482, y: 455, kind: 'empty',  content: null  },
      { x: 90, y: 455, kind: 'veggie', content: 'celery' },
      { x: 510, y: 455, kind: 'veggie', content: 'celery' },
      { x: 62, y: 455, kind: 'veggie', content: 'celery' },
      { x: 538, y: 455, kind: 'veggie', content: 'celery' },
      { x: 188, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 412, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 160, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 440, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 104, y: 480, kind: 'veggie', content: 'celery' },
      { x: 496, y: 480, kind: 'veggie', content: 'celery' },
      { x: 230, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 370, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 528, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 528, kind: 'empty',  content: null  },
      { x: 328, y: 528, kind: 'empty',  content: null  },
      { x: 76, y: 528, kind: 'empty',  content: null  },
      { x: 524, y: 528, kind: 'empty',  content: null  },
      { x: 258, y: 552, kind: 'empty',  content: null  },
      { x: 342, y: 552, kind: 'empty',  content: null  },
      { x: 230, y: 552, kind: 'power',  content: 'split' },
      { x: 370, y: 552, kind: 'power',  content: 'split' },
      { x: 202, y: 552, kind: 'empty',  content: null  },
      { x: 398, y: 552, kind: 'empty',  content: null  },
      { x: 174, y: 552, kind: 'veggie', content: 'broccoli' },
      { x: 426, y: 552, kind: 'veggie', content: 'broccoli' },
      { x: 118, y: 552, kind: 'snack',  content: 'salmon' },
      { x: 482, y: 552, kind: 'snack',  content: 'salmon' },
      { x: 90, y: 552, kind: 'snack',  content: 'salmon', armor: true },
      { x: 510, y: 552, kind: 'snack',  content: 'salmon' },
      { x: 188, y: 576, kind: 'veggie', content: 'celery' },
      { x: 412, y: 576, kind: 'veggie', content: 'celery' },
      { x: 258, y: 601, kind: 'empty',  content: null  },
      { x: 342, y: 601, kind: 'empty',  content: null  },
      { x: 230, y: 601, kind: 'empty',  content: null  },
      { x: 370, y: 601, kind: 'empty',  content: null  },
      { x: 202, y: 601, kind: 'snack',  content: 'tuna' },
      { x: 398, y: 601, kind: 'snack',  content: 'tuna', armor: true },
      { x: 174, y: 601, kind: 'empty',  content: null  },
      { x: 426, y: 601, kind: 'empty',  content: null  },
      { x: 300, y: 625, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 625, kind: 'empty',  content: null  },
      { x: 356, y: 625, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Star Invader',
    balls: 64,
    par: 48,
    goal: 79,
    r: 10,
    vacuum: true,
    barrels: [
      { x: 202, y: 213, kind: 'empty',  content: null  },
      { x: 398, y: 213, kind: 'empty',  content: null  },
      { x: 174, y: 213, kind: 'empty',  content: null  },
      { x: 426, y: 213, kind: 'empty',  content: null  },
      { x: 188, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 412, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 230, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 370, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 244, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 356, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 230, y: 310, kind: 'empty',  content: null  },
      { x: 370, y: 310, kind: 'empty',  content: null  },
      { x: 202, y: 310, kind: 'empty',  content: null  },
      { x: 398, y: 310, kind: 'empty',  content: null  },
      { x: 174, y: 310, kind: 'snack',  content: 'salmon', armor: true },
      { x: 426, y: 310, kind: 'snack',  content: 'salmon', armor: true },
      { x: 300, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 272, y: 334, kind: 'empty',  content: null  },
      { x: 328, y: 334, kind: 'empty',  content: null  },
      { x: 216, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 384, y: 334, kind: 'snack',  content: 'kibble', armor: true },
      { x: 286, y: 358, kind: 'empty',  content: null  },
      { x: 314, y: 358, kind: 'empty',  content: null  },
      { x: 258, y: 358, kind: 'veggie', content: 'broccoli' },
      { x: 342, y: 358, kind: 'veggie', content: 'broccoli' },
      { x: 202, y: 358, kind: 'empty',  content: null  },
      { x: 398, y: 358, kind: 'empty',  content: null  },
      { x: 300, y: 382, kind: 'veggie', content: 'broccoli' },
      { x: 272, y: 382, kind: 'empty',  content: null  },
      { x: 328, y: 382, kind: 'empty',  content: null  },
      { x: 188, y: 382, kind: 'empty',  content: null  },
      { x: 412, y: 382, kind: 'empty',  content: null  },
      { x: 286, y: 407, kind: 'empty',  content: null  },
      { x: 314, y: 407, kind: 'empty',  content: null  },
      { x: 258, y: 407, kind: 'empty',  content: null  },
      { x: 342, y: 407, kind: 'empty',  content: null  },
      { x: 230, y: 407, kind: 'snack',  content: 'tuna', armor: true },
      { x: 370, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 202, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 398, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 174, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 426, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 118, y: 407, kind: 'veggie', content: 'celery' },
      { x: 482, y: 407, kind: 'veggie', content: 'celery' },
      { x: 300, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 328, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 431, kind: 'empty',  content: null  },
      { x: 356, y: 431, kind: 'empty',  content: null  },
      { x: 216, y: 431, kind: 'empty',  content: null  },
      { x: 384, y: 431, kind: 'empty',  content: null  },
      { x: 188, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 412, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 160, y: 431, kind: 'snack',  content: 'salmon', armor: true },
      { x: 440, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 104, y: 431, kind: 'empty',  content: null  },
      { x: 496, y: 431, kind: 'empty',  content: null  },
      { x: 286, y: 455, kind: 'snack',  content: 'salmon', armor: true },
      { x: 314, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 258, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 230, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 370, y: 455, kind: 'snack',  content: 'salmon', armor: true },
      { x: 202, y: 455, kind: 'empty',  content: null  },
      { x: 398, y: 455, kind: 'empty',  content: null  },
      { x: 146, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 454, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 118, y: 455, kind: 'empty',  content: null  },
      { x: 482, y: 455, kind: 'empty',  content: null  },
      { x: 300, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 272, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 328, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 356, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 188, y: 480, kind: 'empty',  content: null  },
      { x: 412, y: 480, kind: 'empty',  content: null  },
      { x: 104, y: 480, kind: 'empty',  content: null  },
      { x: 496, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'empty',  content: null  },
      { x: 314, y: 504, kind: 'empty',  content: null  },
      { x: 258, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 342, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 230, y: 504, kind: 'empty',  content: null  },
      { x: 370, y: 504, kind: 'empty',  content: null  },
      { x: 174, y: 504, kind: 'veggie', content: 'celery' },
      { x: 426, y: 504, kind: 'veggie', content: 'celery' },
      { x: 188, y: 528, kind: 'snack',  content: 'tuna', armor: true },
      { x: 412, y: 528, kind: 'snack',  content: 'tuna' },
      { x: 104, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 496, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 202, y: 552, kind: 'empty',  content: null  },
      { x: 398, y: 552, kind: 'empty',  content: null  },
      { x: 174, y: 552, kind: 'empty',  content: null  },
      { x: 426, y: 552, kind: 'empty',  content: null  },
      { x: 118, y: 552, kind: 'empty',  content: null  },
      { x: 482, y: 552, kind: 'empty',  content: null  },
      { x: 272, y: 576, kind: 'power',  content: 'split' },
      { x: 328, y: 576, kind: 'power',  content: 'split' },
      { x: 244, y: 576, kind: 'empty',  content: null  },
      { x: 356, y: 576, kind: 'empty',  content: null  },
      { x: 216, y: 576, kind: 'empty',  content: null  },
      { x: 384, y: 576, kind: 'empty',  content: null  },
      { x: 258, y: 601, kind: 'empty',  content: null  },
      { x: 342, y: 601, kind: 'empty',  content: null  },
      { x: 230, y: 601, kind: 'empty',  content: null  },
      { x: 370, y: 601, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'Veggie Minefield',
    balls: 66,
    par: 50,
    goal: 87,
    r: 10,
    barrels: [
      { x: 300, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 237, kind: 'empty',  content: null  },
      { x: 328, y: 237, kind: 'empty',  content: null  },
      { x: 188, y: 237, kind: 'empty',  content: null  },
      { x: 412, y: 237, kind: 'empty',  content: null  },
      { x: 160, y: 237, kind: 'empty',  content: null  },
      { x: 440, y: 237, kind: 'empty',  content: null  },
      { x: 132, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 468, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 286, y: 261, kind: 'snack',  content: 'tuna' },
      { x: 314, y: 261, kind: 'snack',  content: 'tuna' },
      { x: 202, y: 261, kind: 'empty',  content: null  },
      { x: 398, y: 261, kind: 'empty',  content: null  },
      { x: 146, y: 261, kind: 'snack',  content: 'tuna' },
      { x: 454, y: 261, kind: 'snack',  content: 'tuna' },
      { x: 118, y: 261, kind: 'empty',  content: null  },
      { x: 482, y: 261, kind: 'empty',  content: null  },
      { x: 300, y: 286, kind: 'empty',  content: null  },
      { x: 272, y: 286, kind: 'veggie', content: 'celery' },
      { x: 328, y: 286, kind: 'veggie', content: 'celery' },
      { x: 244, y: 286, kind: 'snack',  content: 'salmon' },
      { x: 356, y: 286, kind: 'snack',  content: 'salmon', armor: true },
      { x: 258, y: 310, kind: 'snack',  content: 'tuna' },
      { x: 342, y: 310, kind: 'snack',  content: 'tuna' },
      { x: 202, y: 310, kind: 'snack',  content: 'kibble', armor: true },
      { x: 398, y: 310, kind: 'snack',  content: 'kibble', armor: true },
      { x: 174, y: 310, kind: 'empty',  content: null  },
      { x: 426, y: 310, kind: 'empty',  content: null  },
      { x: 118, y: 310, kind: 'snack',  content: 'tuna' },
      { x: 482, y: 310, kind: 'snack',  content: 'tuna' },
      { x: 300, y: 334, kind: 'snack',  content: 'tuna', armor: true },
      { x: 272, y: 334, kind: 'empty',  content: null  },
      { x: 328, y: 334, kind: 'empty',  content: null  },
      { x: 244, y: 334, kind: 'empty',  content: null  },
      { x: 356, y: 334, kind: 'empty',  content: null  },
      { x: 160, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 440, y: 334, kind: 'veggie', content: 'broccoli' },
      { x: 132, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 468, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 286, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 314, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 258, y: 358, kind: 'empty',  content: null  },
      { x: 342, y: 358, kind: 'empty',  content: null  },
      { x: 230, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 370, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 202, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 398, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 174, y: 358, kind: 'empty',  content: null  },
      { x: 426, y: 358, kind: 'empty',  content: null  },
      { x: 146, y: 358, kind: 'empty',  content: null  },
      { x: 454, y: 358, kind: 'empty',  content: null  },
      { x: 132, y: 382, kind: 'empty',  content: null  },
      { x: 468, y: 382, kind: 'empty',  content: null  },
      { x: 104, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 496, y: 382, kind: 'snack',  content: 'salmon' },
      { x: 286, y: 407, kind: 'empty',  content: null  },
      { x: 314, y: 407, kind: 'empty',  content: null  },
      { x: 258, y: 407, kind: 'empty',  content: null  },
      { x: 342, y: 407, kind: 'empty',  content: null  },
      { x: 230, y: 407, kind: 'empty',  content: null  },
      { x: 370, y: 407, kind: 'empty',  content: null  },
      { x: 202, y: 407, kind: 'empty',  content: null  },
      { x: 398, y: 407, kind: 'empty',  content: null  },
      { x: 174, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 426, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 118, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 482, y: 407, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 431, kind: 'veggie', content: 'broccoli' },
      { x: 272, y: 431, kind: 'veggie', content: 'broccoli' },
      { x: 328, y: 431, kind: 'veggie', content: 'broccoli' },
      { x: 216, y: 431, kind: 'empty',  content: null  },
      { x: 384, y: 431, kind: 'empty',  content: null  },
      { x: 188, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 412, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 431, kind: 'empty',  content: null  },
      { x: 468, y: 431, kind: 'empty',  content: null  },
      { x: 104, y: 431, kind: 'empty',  content: null  },
      { x: 496, y: 431, kind: 'empty',  content: null  },
      { x: 174, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 426, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 300, y: 480, kind: 'snack',  content: 'salmon' },
      { x: 272, y: 480, kind: 'empty',  content: null  },
      { x: 328, y: 480, kind: 'empty',  content: null  },
      { x: 216, y: 480, kind: 'empty',  content: null  },
      { x: 384, y: 480, kind: 'empty',  content: null  },
      { x: 132, y: 480, kind: 'empty',  content: null  },
      { x: 468, y: 480, kind: 'empty',  content: null  },
      { x: 104, y: 480, kind: 'empty',  content: null  },
      { x: 496, y: 480, kind: 'empty',  content: null  },
      { x: 174, y: 504, kind: 'empty',  content: null  },
      { x: 426, y: 504, kind: 'empty',  content: null  },
      { x: 118, y: 504, kind: 'empty',  content: null  },
      { x: 482, y: 504, kind: 'empty',  content: null  },
      { x: 300, y: 528, kind: 'empty',  content: null  },
      { x: 272, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 328, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 216, y: 528, kind: 'empty',  content: null  },
      { x: 384, y: 528, kind: 'empty',  content: null  },
      { x: 188, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 412, y: 528, kind: 'snack',  content: 'kibble' },
      { x: 160, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 440, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 286, y: 552, kind: 'snack',  content: 'kibble' },
      { x: 314, y: 552, kind: 'snack',  content: 'kibble' },
      { x: 258, y: 552, kind: 'power',  content: 'split' },
      { x: 342, y: 552, kind: 'power',  content: 'split' },
      { x: 146, y: 552, kind: 'empty',  content: null  },
      { x: 454, y: 552, kind: 'empty',  content: null  },
      { x: 118, y: 552, kind: 'snack',  content: 'kibble' },
      { x: 482, y: 552, kind: 'snack',  content: 'kibble' },
    ],
  },
  {
    name: 'Power Tower',
    balls: 68,
    par: 51,
    goal: 98,
    r: 10,
    barrels: [
      { x: 300, y: 188, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 188, kind: 'snack',  content: 'kibble' },
      { x: 356, y: 188, kind: 'snack',  content: 'kibble' },
      { x: 286, y: 213, kind: 'empty',  content: null  },
      { x: 314, y: 213, kind: 'empty',  content: null  },
      { x: 272, y: 237, kind: 'empty',  content: null  },
      { x: 328, y: 237, kind: 'empty',  content: null  },
      { x: 286, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 314, y: 261, kind: 'snack',  content: 'salmon' },
      { x: 258, y: 261, kind: 'empty',  content: null  },
      { x: 342, y: 261, kind: 'empty',  content: null  },
      { x: 300, y: 286, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 286, kind: 'veggie', content: 'broccoli' },
      { x: 356, y: 286, kind: 'veggie', content: 'broccoli' },
      { x: 286, y: 310, kind: 'power',  content: 'split' },
      { x: 314, y: 310, kind: 'power',  content: 'split' },
      { x: 258, y: 310, kind: 'empty',  content: null  },
      { x: 342, y: 310, kind: 'empty',  content: null  },
      { x: 300, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 334, kind: 'snack',  content: 'kibble', armor: true },
      { x: 356, y: 334, kind: 'snack',  content: 'kibble' },
      { x: 286, y: 358, kind: 'empty',  content: null  },
      { x: 314, y: 358, kind: 'empty',  content: null  },
      { x: 258, y: 358, kind: 'empty',  content: null  },
      { x: 342, y: 358, kind: 'empty',  content: null  },
      { x: 202, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 398, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 174, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 426, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 510, y: 358, kind: 'snack',  content: 'tuna' },
      { x: 62, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 538, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 300, y: 382, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 382, kind: 'power',  content: 'magnet' },
      { x: 328, y: 382, kind: 'power',  content: 'magnet' },
      { x: 216, y: 382, kind: 'snack',  content: 'tuna', armor: true },
      { x: 384, y: 382, kind: 'snack',  content: 'tuna' },
      { x: 188, y: 382, kind: 'empty',  content: null  },
      { x: 412, y: 382, kind: 'empty',  content: null  },
      { x: 132, y: 382, kind: 'empty',  content: null  },
      { x: 468, y: 382, kind: 'empty',  content: null  },
      { x: 104, y: 382, kind: 'empty',  content: null  },
      { x: 496, y: 382, kind: 'empty',  content: null  },
      { x: 76, y: 382, kind: 'empty',  content: null  },
      { x: 524, y: 382, kind: 'empty',  content: null  },
      { x: 258, y: 407, kind: 'empty',  content: null  },
      { x: 342, y: 407, kind: 'empty',  content: null  },
      { x: 230, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 370, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 202, y: 407, kind: 'empty',  content: null  },
      { x: 398, y: 407, kind: 'empty',  content: null  },
      { x: 146, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 454, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 118, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 482, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 510, y: 407, kind: 'snack',  content: 'tuna' },
      { x: 62, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 538, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 300, y: 431, kind: 'empty',  content: null  },
      { x: 244, y: 431, kind: 'empty',  content: null  },
      { x: 356, y: 431, kind: 'empty',  content: null  },
      { x: 216, y: 431, kind: 'empty',  content: null  },
      { x: 384, y: 431, kind: 'empty',  content: null  },
      { x: 188, y: 431, kind: 'empty',  content: null  },
      { x: 412, y: 431, kind: 'empty',  content: null  },
      { x: 160, y: 431, kind: 'empty',  content: null  },
      { x: 440, y: 431, kind: 'empty',  content: null  },
      { x: 132, y: 431, kind: 'veggie', content: 'celery' },
      { x: 468, y: 431, kind: 'veggie', content: 'celery' },
      { x: 104, y: 431, kind: 'snack',  content: 'salmon', armor: true },
      { x: 496, y: 431, kind: 'snack',  content: 'salmon' },
      { x: 76, y: 431, kind: 'empty',  content: null  },
      { x: 524, y: 431, kind: 'empty',  content: null  },
      { x: 286, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 314, y: 455, kind: 'snack',  content: 'tuna', armor: true },
      { x: 230, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 370, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 202, y: 455, kind: 'empty',  content: null  },
      { x: 398, y: 455, kind: 'empty',  content: null  },
      { x: 174, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 426, y: 455, kind: 'snack',  content: 'salmon' },
      { x: 118, y: 455, kind: 'empty',  content: null  },
      { x: 482, y: 455, kind: 'empty',  content: null  },
      { x: 90, y: 455, kind: 'veggie', content: 'broccoli' },
      { x: 510, y: 455, kind: 'veggie', content: 'broccoli' },
      { x: 272, y: 480, kind: 'snack',  content: 'tuna', armor: true },
      { x: 328, y: 480, kind: 'snack',  content: 'tuna' },
      { x: 244, y: 480, kind: 'empty',  content: null  },
      { x: 356, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'veggie', content: 'celery' },
      { x: 314, y: 504, kind: 'veggie', content: 'celery' },
      { x: 258, y: 504, kind: 'empty',  content: null  },
      { x: 342, y: 504, kind: 'empty',  content: null  },
      { x: 300, y: 528, kind: 'empty',  content: null  },
      { x: 272, y: 528, kind: 'empty',  content: null  },
      { x: 328, y: 528, kind: 'empty',  content: null  },
      { x: 244, y: 528, kind: 'empty',  content: null  },
      { x: 356, y: 528, kind: 'empty',  content: null  },
      { x: 286, y: 552, kind: 'empty',  content: null  },
      { x: 314, y: 552, kind: 'empty',  content: null  },
      { x: 258, y: 552, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 552, kind: 'snack',  content: 'salmon', armor: true },
      { x: 300, y: 576, kind: 'empty',  content: null  },
      { x: 272, y: 576, kind: 'snack',  content: 'tuna' },
      { x: 328, y: 576, kind: 'snack',  content: 'tuna' },
      { x: 286, y: 601, kind: 'empty',  content: null  },
      { x: 314, y: 601, kind: 'empty',  content: null  },
      { x: 258, y: 601, kind: 'empty',  content: null  },
      { x: 342, y: 601, kind: 'empty',  content: null  },
      { x: 300, y: 625, kind: 'veggie', content: 'broccoli' },
      { x: 244, y: 625, kind: 'empty',  content: null  },
      { x: 356, y: 625, kind: 'empty',  content: null  },
    ],
  },
  {
    name: 'The Grand Feast',
    balls: 72,
    par: 54,
    goal: 103,
    r: 10,
    vacuum: true,
    barrels: [
      { x: 300, y: 188, kind: 'snack',  content: 'kibble' },
      { x: 272, y: 188, kind: 'empty',  content: null  },
      { x: 328, y: 188, kind: 'empty',  content: null  },
      { x: 258, y: 213, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 213, kind: 'snack',  content: 'salmon' },
      { x: 230, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 370, y: 213, kind: 'snack',  content: 'tuna' },
      { x: 146, y: 213, kind: 'veggie', content: 'broccoli' },
      { x: 454, y: 213, kind: 'veggie', content: 'broccoli' },
      { x: 90, y: 213, kind: 'empty',  content: null  },
      { x: 510, y: 213, kind: 'empty',  content: null  },
      { x: 62, y: 213, kind: 'empty',  content: null  },
      { x: 538, y: 213, kind: 'empty',  content: null  },
      { x: 300, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 272, y: 237, kind: 'empty',  content: null  },
      { x: 328, y: 237, kind: 'empty',  content: null  },
      { x: 188, y: 237, kind: 'snack',  content: 'tuna' },
      { x: 412, y: 237, kind: 'snack',  content: 'tuna', armor: true },
      { x: 132, y: 237, kind: 'empty',  content: null  },
      { x: 468, y: 237, kind: 'empty',  content: null  },
      { x: 230, y: 261, kind: 'empty',  content: null  },
      { x: 370, y: 261, kind: 'empty',  content: null  },
      { x: 118, y: 261, kind: 'empty',  content: null  },
      { x: 482, y: 261, kind: 'empty',  content: null  },
      { x: 62, y: 261, kind: 'empty',  content: null  },
      { x: 538, y: 261, kind: 'empty',  content: null  },
      { x: 300, y: 286, kind: 'veggie', content: 'broccoli' },
      { x: 216, y: 286, kind: 'empty',  content: null  },
      { x: 384, y: 286, kind: 'empty',  content: null  },
      { x: 160, y: 286, kind: 'veggie', content: 'broccoli' },
      { x: 440, y: 286, kind: 'veggie', content: 'broccoli' },
      { x: 132, y: 286, kind: 'empty',  content: null  },
      { x: 468, y: 286, kind: 'empty',  content: null  },
      { x: 104, y: 286, kind: 'power',  content: 'split' },
      { x: 496, y: 286, kind: 'power',  content: 'split' },
      { x: 258, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 342, y: 310, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 216, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 384, y: 334, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 334, kind: 'empty',  content: null  },
      { x: 468, y: 334, kind: 'empty',  content: null  },
      { x: 286, y: 358, kind: 'snack',  content: 'kibble', armor: true },
      { x: 314, y: 358, kind: 'snack',  content: 'kibble' },
      { x: 258, y: 358, kind: 'empty',  content: null  },
      { x: 342, y: 358, kind: 'empty',  content: null  },
      { x: 118, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 482, y: 358, kind: 'snack',  content: 'salmon' },
      { x: 90, y: 358, kind: 'empty',  content: null  },
      { x: 510, y: 358, kind: 'empty',  content: null  },
      { x: 300, y: 382, kind: 'veggie', content: 'broccoli' },
      { x: 272, y: 382, kind: 'snack',  content: 'tuna' },
      { x: 328, y: 382, kind: 'snack',  content: 'tuna', armor: true },
      { x: 244, y: 382, kind: 'empty',  content: null  },
      { x: 356, y: 382, kind: 'empty',  content: null  },
      { x: 132, y: 382, kind: 'snack',  content: 'tuna' },
      { x: 468, y: 382, kind: 'snack',  content: 'tuna' },
      { x: 258, y: 407, kind: 'empty',  content: null  },
      { x: 342, y: 407, kind: 'empty',  content: null  },
      { x: 90, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 510, y: 407, kind: 'snack',  content: 'salmon' },
      { x: 62, y: 407, kind: 'empty',  content: null  },
      { x: 538, y: 407, kind: 'empty',  content: null  },
      { x: 300, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 188, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 412, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 132, y: 431, kind: 'empty',  content: null  },
      { x: 468, y: 431, kind: 'empty',  content: null  },
      { x: 104, y: 431, kind: 'snack',  content: 'tuna', armor: true },
      { x: 496, y: 431, kind: 'snack',  content: 'tuna' },
      { x: 258, y: 455, kind: 'veggie', content: 'celery' },
      { x: 342, y: 455, kind: 'veggie', content: 'celery' },
      { x: 174, y: 455, kind: 'snack',  content: 'tuna', armor: true },
      { x: 426, y: 455, kind: 'snack',  content: 'tuna' },
      { x: 62, y: 455, kind: 'empty',  content: null  },
      { x: 538, y: 455, kind: 'empty',  content: null  },
      { x: 272, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 328, y: 480, kind: 'veggie', content: 'broccoli' },
      { x: 188, y: 480, kind: 'veggie', content: 'celery' },
      { x: 412, y: 480, kind: 'veggie', content: 'celery' },
      { x: 160, y: 480, kind: 'empty',  content: null  },
      { x: 440, y: 480, kind: 'empty',  content: null  },
      { x: 132, y: 480, kind: 'empty',  content: null  },
      { x: 468, y: 480, kind: 'empty',  content: null  },
      { x: 286, y: 504, kind: 'snack',  content: 'tuna' },
      { x: 314, y: 504, kind: 'snack',  content: 'tuna' },
      { x: 230, y: 504, kind: 'empty',  content: null  },
      { x: 370, y: 504, kind: 'empty',  content: null  },
      { x: 202, y: 504, kind: 'empty',  content: null  },
      { x: 398, y: 504, kind: 'empty',  content: null  },
      { x: 146, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 454, y: 504, kind: 'veggie', content: 'broccoli' },
      { x: 300, y: 528, kind: 'empty',  content: null  },
      { x: 244, y: 528, kind: 'empty',  content: null  },
      { x: 356, y: 528, kind: 'empty',  content: null  },
      { x: 188, y: 528, kind: 'snack',  content: 'salmon' },
      { x: 412, y: 528, kind: 'snack',  content: 'salmon', armor: true },
      { x: 286, y: 552, kind: 'empty',  content: null  },
      { x: 314, y: 552, kind: 'empty',  content: null  },
      { x: 258, y: 552, kind: 'snack',  content: 'tuna' },
      { x: 342, y: 552, kind: 'snack',  content: 'tuna' },
      { x: 90, y: 552, kind: 'snack',  content: 'tuna' },
      { x: 510, y: 552, kind: 'snack',  content: 'tuna' },
      { x: 300, y: 576, kind: 'snack',  content: 'salmon' },
      { x: 244, y: 576, kind: 'empty',  content: null  },
      { x: 356, y: 576, kind: 'empty',  content: null  },
      { x: 216, y: 576, kind: 'empty',  content: null  },
      { x: 384, y: 576, kind: 'empty',  content: null  },
      { x: 160, y: 576, kind: 'empty',  content: null  },
      { x: 440, y: 576, kind: 'empty',  content: null  },
      { x: 104, y: 576, kind: 'empty',  content: null  },
      { x: 496, y: 576, kind: 'empty',  content: null  },
      { x: 258, y: 601, kind: 'snack',  content: 'salmon' },
      { x: 342, y: 601, kind: 'snack',  content: 'salmon', armor: true },
      { x: 230, y: 601, kind: 'empty',  content: null  },
      { x: 370, y: 601, kind: 'empty',  content: null  },
      { x: 146, y: 601, kind: 'snack',  content: 'tuna' },
      { x: 454, y: 601, kind: 'snack',  content: 'tuna' },
      { x: 118, y: 601, kind: 'empty',  content: null  },
      { x: 482, y: 601, kind: 'empty',  content: null  },
    ],
  },
];
